import json
import os

data = [
  # Day 56
  {
    "id": "front desk agent-phrase",
    "word": "front desk agent",
    "baseWord": "agent",
    "type": "phrase",
    "meaning": "nhân viên lễ tân",
    "pronunciation": "/frʌnt desk ˈeɪdʒənt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The front desk agent handed us our keycards and explained the hotel amenities.",
    "exampleVi": "Nhân viên lễ tân đã đưa thẻ khóa cho chúng tôi và giải thích các tiện nghi của khách sạn.",
    "collocations": ["professional front desk agent", "ask the front desk agent", "front desk agent duties"],
    "synonyms": ["receptionist", "hotel clerk"],
    "wordFamily": ["front", "desk", "agent", "agency"],
    "day": 56
  },
  {
    "id": "front desk clerk-phrase",
    "word": "front desk clerk",
    "baseWord": "clerk",
    "type": "phrase",
    "meaning": "nhân viên bàn tiếp tân",
    "pronunciation": "/frʌnt desk klɜːrk/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Please inform the front desk clerk if you need extra towels.",
    "exampleVi": "Vui lòng thông báo cho nhân viên bàn tiếp tân nếu bạn cần thêm khăn tắm.",
    "collocations": ["check in with the front desk clerk", "helpful front desk clerk"],
    "synonyms": ["desk clerk", "receptionist"],
    "wordFamily": ["front", "desk", "clerk", "clerical"],
    "day": 56
  },
  {
    "id": "welcome amenity-phrase",
    "word": "welcome amenity",
    "baseWord": "amenity",
    "type": "phrase",
    "meaning": "tiện nghi chào mừng, quà chào mừng",
    "pronunciation": "/ˈwelkəm əˈmiːnəti/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 5", "Part 7"],
    "example": "A basket of fresh fruit was placed in our suite as a welcome amenity.",
    "exampleVi": "Một giỏ trái cây tươi đã được đặt trong phòng suite của chúng tôi như một món quà chào mừng.",
    "collocations": ["complimentary welcome amenity", "welcome amenity package"],
    "synonyms": ["welcome gift", "complimentary gift"],
    "wordFamily": ["welcome", "amenity", "amenities"],
    "day": 56
  },
  {
    "id": "valet parking-phrase",
    "word": "valet parking",
    "baseWord": "park",
    "type": "phrase",
    "meaning": "dịch vụ đỗ xe hộ",
    "pronunciation": "/væˈleɪ ˈpɑːrkɪŋ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The hotel offers complimentary valet parking for all overnight guests.",
    "exampleVi": "Khách sạn cung cấp dịch vụ đỗ xe hộ miễn phí cho tất cả khách lưu trú qua đêm.",
    "collocations": ["valet parking service", "valet parking attendant", "use valet parking"],
    "synonyms": ["valet service"],
    "wordFamily": ["valet", "park", "parking"],
    "day": 56
  },
  {
    "id": "bellhop-noun",
    "word": "bellhop",
    "baseWord": "bellhop",
    "type": "noun",
    "meaning": "nhân viên hành lý khách sạn",
    "pronunciation": "/ˈbelhɑːp/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The bellhop helped us carry our heavy suitcases up to the room.",
    "exampleVi": "Nhân viên hành lý đã giúp chúng tôi mang những chiếc vali nặng lên phòng.",
    "collocations": ["tip the bellhop", "bellhop service"],
    "synonyms": ["porter", "baggage handler"],
    "wordFamily": ["bell", "hop"],
    "day": 56
  },
  {
    "id": "amenities-noun",
    "word": "amenities",
    "baseWord": "amenity",
    "type": "noun",
    "meaning": "các tiện nghi, dịch vụ đi kèm",
    "pronunciation": "/əˈmenətiz/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The resort offers excellent amenities, including a spa and a heated pool.",
    "exampleVi": "Khu nghỉ dưỡng cung cấp các tiện nghi tuyệt vời, bao gồm một spa và một hồ bơi nước ấm.",
    "collocations": ["hotel amenities", "basic amenities", "luxury amenities"],
    "synonyms": ["facilities", "features", "conveniences"],
    "wordFamily": ["amenity"],
    "day": 56
  },
  {
    "id": "housekeeper-noun",
    "word": "housekeeper",
    "baseWord": "housekeep",
    "type": "noun",
    "meaning": "nhân viên dọn phòng",
    "pronunciation": "/ˈhaʊskiːpər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The housekeeper will change the bed linen and vacuum the carpet.",
    "exampleVi": "Nhân viên dọn phòng sẽ thay ga trải giường và hút bụi thảm.",
    "collocations": ["hotel housekeeper", "housekeeper duties", "head housekeeper"],
    "synonyms": ["chambermaid", "cleaner"],
    "wordFamily": ["housekeep", "housekeeping"],
    "day": 56
  },
  {
    "id": "maid service-phrase",
    "word": "maid service",
    "baseWord": "service",
    "type": "phrase",
    "meaning": "dịch vụ dọn dẹp phòng",
    "pronunciation": "/meɪd ˈsɜːrvɪs/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 5", "Part 7"],
    "example": "Daily maid service is included in the price of your hotel room.",
    "exampleVi": "Dịch vụ dọn dẹp phòng hàng ngày được bao gồm trong giá phòng khách sạn của bạn.",
    "collocations": ["daily maid service", "request maid service", "opt out of maid service"],
    "synonyms": ["cleaning service", "housekeeping service"],
    "wordFamily": ["maid", "serve", "service"],
    "day": 56
  },
  {
    "id": "vacant room-phrase",
    "word": "vacant room",
    "baseWord": "vacant",
    "type": "phrase",
    "meaning": "phòng trống",
    "pronunciation": "/ˈveɪkənt ruːm/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The receptionist checked the computer system to see if there was a vacant room.",
    "exampleVi": "Nhân viên lễ tân đã kiểm tra hệ thống máy tính xem có phòng trống nào không.",
    "collocations": ["find a vacant room", "no vacant rooms available"],
    "synonyms": ["empty room", "available room"],
    "wordFamily": ["vacant", "vacancy", "vacate"],
    "day": 56
  },
  {
    "id": "occupancy-noun",
    "word": "occupancy",
    "baseWord": "occupy",
    "type": "noun",
    "meaning": "công suất sử dụng phòng, tỷ lệ thuê",
    "pronunciation": "/ˈɑːkjəpənsi/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 5", "Part 7"],
    "example": "Hotel occupancy rates usually peak during the summer tourist season.",
    "exampleVi": "Tỷ lệ thuê phòng khách sạn thường đạt đỉnh vào mùa du lịch hè.",
    "collocations": ["occupancy rate", "hotel occupancy", "maximum occupancy"],
    "synonyms": ["tenancy", "possession", "inhabitation"],
    "wordFamily": ["occupy", "occupant", "occupational"],
    "day": 56
  },
  {
    "id": "unoccupied-adjective",
    "word": "unoccupied",
    "baseWord": "occupy",
    "type": "adjective",
    "meaning": "còn trống, chưa có người thuê",
    "pronunciation": "/ʌnˈɑːkjəpaɪd/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 5", "Part 7"],
    "example": "Only a few tables in the dining room remained unoccupied.",
    "exampleVi": "Chỉ còn vài bàn trong phòng ăn là vẫn chưa có người ngồi.",
    "collocations": ["remain unoccupied", "unoccupied building", "unoccupied room"],
    "synonyms": ["vacant", "empty", "uninhabited"],
    "wordFamily": ["occupy", "occupant", "occupied"],
    "day": 56
  },
  {
    "id": "waitstaff-noun",
    "word": "waitstaff",
    "baseWord": "staff",
    "type": "noun",
    "meaning": "đội ngũ nhân viên phục vụ bàn",
    "pronunciation": "/ˈweɪtstæf/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The waitstaff at this restaurant are known for their prompt and friendly service.",
    "exampleVi": "Đội ngũ phục vụ bàn tại nhà hàng này nổi tiếng với sự phục vụ nhanh chóng và thân thiện.",
    "collocations": ["experienced waitstaff", "tip the waitstaff", "waitstaff training"],
    "synonyms": ["servers", "waiters and waitresses"],
    "wordFamily": ["wait", "staff"],
    "day": 56
  },
  {
    "id": "waiter-noun",
    "word": "waiter",
    "baseWord": "wait",
    "type": "noun",
    "meaning": "nam nhân viên phục vụ bàn",
    "pronunciation": "/ˈweɪtər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The waiter recommended the seafood pasta as today's special.",
    "exampleVi": "Nam nhân viên phục vụ khuyên dùng món mỳ Ý hải sản như một món đặc biệt hôm nay.",
    "collocations": ["call the waiter", "ask the waiter"],
    "synonyms": ["server", "waitperson"],
    "wordFamily": ["wait", "waitress"],
    "day": 56
  },
  {
    "id": "waitress-noun",
    "word": "waitress",
    "baseWord": "wait",
    "type": "noun",
    "meaning": "nữ nhân viên phục vụ bàn",
    "pronunciation": "/ˈweɪtrəs/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The waitress quickly cleared the empty plates from our table.",
    "exampleVi": "Nữ nhân viên phục vụ nhanh chóng dọn những chiếc đĩa trống khỏi bàn của chúng tôi.",
    "collocations": ["friendly waitress", "ask the waitress"],
    "synonyms": ["server", "waitperson"],
    "wordFamily": ["wait", "waiter"],
    "day": 56
  },
  {
    "id": "gratuity-noun",
    "word": "gratuity",
    "baseWord": "gratuity",
    "type": "noun",
    "meaning": "tiền boa, tiền phí dịch vụ",
    "pronunciation": "/ɡrəˈtuːəti/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "hard",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "A fifteen percent gratuity is automatically added to parties of six or more.",
    "exampleVi": "Tiền boa mười lăm phần trăm sẽ tự động được thêm vào cho các nhóm từ sáu người trở lên.",
    "collocations": ["include gratuity", "gratuity not included", "cash gratuity"],
    "synonyms": ["tip", "service charge"],
    "wordFamily": ["gratitude", "grateful"],
    "day": 56
  },
  {
    "id": "tip-noun",
    "word": "tip",
    "baseWord": "tip",
    "type": "noun",
    "meaning": "tiền boa, tiền thưởng nhỏ, mẹo nhỏ",
    "pronunciation": "/tɪp/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "It is customary to leave a generous tip for outstanding restaurant service.",
    "exampleVi": "Để lại một khoản tiền boa hào phóng cho dịch vụ nhà hàng xuất sắc là một thông lệ.",
    "collocations": ["leave a tip", "generous tip", "give a tip"],
    "synonyms": ["gratuity", "baksheesh"],
    "wordFamily": ["tip", "tipping"],
    "day": 56
  },
  {
    "id": "refill-verb",
    "word": "refill",
    "baseWord": "fill",
    "type": "verb",
    "meaning": "làm đầy lại, rót thêm nước",
    "pronunciation": "/ˌriːˈfɪl/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Our server offered to refill our glasses with iced tea.",
    "exampleVi": "Người phục vụ đề nghị rót đầy lại trà đá vào ly của chúng tôi.",
    "collocations": ["refill a drink", "refill a prescription", "free refills"],
    "synonyms": ["replenish", "top up"],
    "wordFamily": ["fill", "refillable"],
    "day": 56
  },
  {
    "id": "ingredient-noun",
    "word": "ingredient",
    "baseWord": "ingredient",
    "type": "noun",
    "meaning": "thành phần, nguyên liệu nấu ăn",
    "pronunciation": "/ɪnˈɡriːdiənt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "This restaurant prides itself on using only fresh, locally sourced ingredients.",
    "exampleVi": "Nhà hàng này tự hào chỉ sử dụng những nguyên liệu tươi ngon, có nguồn gốc địa phương.",
    "collocations": ["fresh ingredients", "key ingredient", "active ingredient"],
    "synonyms": ["component", "element", "constituent"],
    "wordFamily": ["ingredient"],
    "day": 56
  },
  {
    "id": "house specialty-phrase",
    "word": "house specialty",
    "baseWord": "special",
    "type": "phrase",
    "meaning": "món ăn đặc sản của nhà hàng",
    "pronunciation": "/haʊs ˈspeʃəlti/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The roasted duck is a house specialty that you must try.",
    "exampleVi": "Vịt quay là một món ăn đặc sản của nhà hàng mà bạn nhất định phải thử.",
    "collocations": ["try the house specialty", "signature house specialty"],
    "synonyms": ["signature dish", "specialty of the house"],
    "wordFamily": ["house", "special", "specialty"],
    "day": 56
  },
  {
    "id": "room booking-phrase",
    "word": "room booking",
    "baseWord": "book",
    "type": "phrase",
    "meaning": "việc đặt phòng khách sạn",
    "pronunciation": "/ruːm ˈbʊkɪŋ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "I would like to modify my room booking from a single to a double room.",
    "exampleVi": "Tôi muốn thay đổi việc đặt phòng của mình từ phòng đơn sang phòng đôi.",
    "collocations": ["confirm a room booking", "cancel a room booking", "online room booking"],
    "synonyms": ["room reservation", "hotel reservation"],
    "wordFamily": ["book", "booking", "room"],
    "day": 56
  },

  # Day 57
  {
    "id": "host-noun",
    "word": "host",
    "baseWord": "host",
    "type": "noun",
    "meaning": "chủ nhà, người dẫn chương trình",
    "pronunciation": "/hoʊst/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The host welcomed the delegation and showed them to their tables.",
    "exampleVi": "Người tiếp đón đã chào mừng đoàn đại biểu và đưa họ đến bàn của mình.",
    "collocations": ["gracious host", "play host to", "host country"],
    "synonyms": ["MC", "presenter", "receptionist"],
    "wordFamily": ["hostess", "hosting", "host"],
    "day": 57
  },
  {
    "id": "hostess-noun",
    "word": "hostess",
    "baseWord": "host",
    "type": "noun",
    "meaning": "nữ tiếp đón khách (ở nhà hàng)",
    "pronunciation": "/ˈhoʊstəs/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The hostess escorted us to our reserved booth near the window.",
    "exampleVi": "Nữ tiếp đón đã hộ tống chúng tôi đến bàn ăn được đặt trước gần cửa sổ.",
    "collocations": ["restaurant hostess", "ask the hostess"],
    "synonyms": ["receptionist", "greeter"],
    "wordFamily": ["host", "hosting"],
    "day": 57
  },
  {
    "id": "banquet-noun",
    "word": "banquet",
    "baseWord": "banquet",
    "type": "noun",
    "meaning": "yến tiệc, bữa tiệc lớn",
    "pronunciation": "/ˈbæŋkwɪt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The awards ceremony was followed by a grand banquet in the hotel ballroom.",
    "exampleVi": "Lễ trao giải được tiếp nối bởi một bữa tiệc lớn tại phòng đại tiệc của khách sạn.",
    "collocations": ["awards banquet", "annual banquet", "banquet hall"],
    "synonyms": ["feast", "dinner", "celebration"],
    "wordFamily": ["banquet", "banqueting"],
    "day": 57
  },
  {
    "id": "catering service-phrase",
    "word": "catering service",
    "baseWord": "cater",
    "type": "phrase",
    "meaning": "dịch vụ cung cấp tiệc ăn uống",
    "pronunciation": "/ˈkeɪtərɪŋ ˈsɜːrvɪs/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We hired a local catering service to provide food for the conference.",
    "exampleVi": "Chúng tôi đã thuê một dịch vụ cung cấp tiệc địa phương để chuẩn bị đồ ăn cho hội nghị.",
    "collocations": ["professional catering service", "hire a catering service"],
    "synonyms": ["catering company", "food service"],
    "wordFamily": ["cater", "caterer", "catering"],
    "day": 57
  },
  {
    "id": "caterer-noun",
    "word": "caterer",
    "baseWord": "cater",
    "type": "noun",
    "meaning": "nhà cung cấp dịch vụ ăn uống",
    "pronunciation": "/ˈkeɪtərər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The caterer arrived early to set up the buffet tables.",
    "exampleVi": "Nhà cung cấp dịch vụ ăn uống đã đến sớm để bày các bàn tiệc đứng.",
    "collocations": ["event caterer", "find a reliable caterer"],
    "synonyms": ["food provider", "caterer service"],
    "wordFamily": ["cater", "catering"],
    "day": 57
  },
  {
    "id": "dine-in-phrase",
    "word": "dine-in",
    "baseWord": "dine",
    "type": "phrase",
    "meaning": "ăn tại chỗ, dùng bữa tại nhà hàng",
    "pronunciation": "/ˈdaɪn ɪn/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Do you want this order to go, or is it for dine-in?",
    "exampleVi": "Bạn muốn mang đơn hàng này đi, hay dùng tại chỗ?",
    "collocations": ["dine-in customer", "dine-in option", "dine-in service"],
    "synonyms": ["eat in", "table service"],
    "wordFamily": ["dine", "diner", "dining"],
    "day": 57
  },
  {
    "id": "take-out-phrase",
    "word": "take-out",
    "baseWord": "take",
    "type": "phrase",
    "meaning": "mang thức ăn đi, mua mang về",
    "pronunciation": "/ˈteɪk aʊt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Let's order some take-out from the Italian restaurant down the street.",
    "exampleVi": "Hãy đặt món mang về từ nhà hàng Ý ở phía cuối đường.",
    "collocations": ["order take-out", "take-out food", "take-out menu"],
    "synonyms": ["takeaway", "to-go food"],
    "wordFamily": ["take", "out"],
    "day": 57
  },
  {
    "id": "utensil-noun",
    "word": "utensil",
    "baseWord": "utensil",
    "type": "noun",
    "meaning": "dụng cụ, đồ dùng nhà bếp/ăn uống",
    "pronunciation": "/juːˈtensl/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The waiter placed the eating utensils next to the soup bowl.",
    "exampleVi": "Người phục vụ đặt các dụng cụ ăn uống bên cạnh bát súp.",
    "collocations": ["eating utensils", "kitchen utensils", "cooking utensils"],
    "synonyms": ["tool", "implement", "instrument"],
    "wordFamily": ["utility", "utilize"],
    "day": 57
  },
  {
    "id": "cutlery-noun",
    "word": "cutlery",
    "baseWord": "cut",
    "type": "noun",
    "meaning": "dao dĩa muỗng để ăn",
    "pronunciation": "/ˈkʌtləri/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "Stainless steel cutlery is durable and easy to clean.",
    "exampleVi": "Dao dĩa bằng thép không gỉ thì bền và dễ lau chùi.",
    "collocations": ["set of cutlery", "stainless steel cutlery", "silver cutlery"],
    "synonyms": ["silverware", "flatware"],
    "wordFamily": ["cut", "cutter"],
    "day": 57
  },
  {
    "id": "tableware-noun",
    "word": "tableware",
    "baseWord": "table",
    "type": "noun",
    "meaning": "bộ đồ ăn (chén, đĩa, ly)",
    "pronunciation": "/ˈteɪblwer/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 1", "Part 5"],
    "example": "The catering staff is setting up the tableware for the dinner banquet.",
    "exampleVi": "Nhân viên phục vụ tiệc đang sắp xếp bộ đồ ăn cho bữa tiệc tối.",
    "collocations": ["ceramic tableware", "fine tableware", "set the tableware"],
    "synonyms": ["dinnerware", "dishes"],
    "wordFamily": ["table", "ware"],
    "day": 57
  },
  {
    "id": "napkin-noun",
    "word": "napkin",
    "baseWord": "napkin",
    "type": "noun",
    "meaning": "khăn ăn",
    "pronunciation": "/ˈnæpkɪn/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "She wiped her hands with a paper napkin after finishing her sandwich.",
    "exampleVi": "Cô ấy đã lau tay bằng khăn giấy sau khi ăn xong bánh sandwich.",
    "collocations": ["paper napkin", "cloth napkin", "fold a napkin"],
    "synonyms": ["serviette"],
    "wordFamily": ["napkin"],
    "day": 57
  },
  {
    "id": "tablecloth-noun",
    "word": "tablecloth",
    "baseWord": "table",
    "type": "noun",
    "meaning": "khăn trải bàn",
    "pronunciation": "/ˈteɪblklaːθ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 5"],
    "example": "The staff draped a white linen tablecloth over each table.",
    "exampleVi": "Nhân viên đã phủ một chiếc khăn trải bàn bằng vải lanh trắng lên mỗi bàn.",
    "collocations": ["linen tablecloth", "stain on the tablecloth"],
    "synonyms": ["table cover"],
    "wordFamily": ["table", "cloth"],
    "day": 57
  },
  {
    "id": "saucer-noun",
    "word": "saucer",
    "baseWord": "saucer",
    "type": "noun",
    "meaning": "đĩa lót tách/chén",
    "pronunciation": "/ˈsɔːsər/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 1", "Part 5"],
    "example": "He placed the coffee cup carefully back onto the saucer.",
    "exampleVi": "Anh đặt tách cà phê cẩn thận trở lại đĩa lót.",
    "collocations": ["cup and saucer", "ceramic saucer"],
    "synonyms": ["small dish", "platelet"],
    "wordFamily": ["sauce", "saucer"],
    "day": 57
  },
  {
    "id": "pitcher-noun",
    "word": "pitcher",
    "baseWord": "pitcher",
    "type": "noun",
    "meaning": "bình đựng nước (có tay cầm, vòi rót)",
    "pronunciation": "/ˈpɪtʃər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The waiter brought a pitcher of ice water to our table.",
    "exampleVi": "Người phục vụ mang một bình nước đá đến bàn của chúng tôi.",
    "collocations": ["pitcher of water", "glass pitcher", "fill the pitcher"],
    "synonyms": ["jug", "carafe"],
    "wordFamily": ["pitch", "pitcher"],
    "day": 57
  },
  {
    "id": "dietary-adjective",
    "word": "dietary",
    "baseWord": "diet",
    "type": "adjective",
    "meaning": "thuộc về chế độ ăn uống",
    "pronunciation": "/ˈdaɪəteri/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Please let us know if you have any special dietary requirements.",
    "exampleVi": "Vui lòng cho chúng tôi biết nếu bạn có bất kỳ yêu cầu đặc biệt nào về chế độ ăn uống.",
    "collocations": ["dietary requirements", "dietary restrictions", "dietary guidelines"],
    "synonyms": ["nutritional", "dietetic"],
    "wordFamily": ["diet", "dietician"],
    "day": 57
  },
  {
    "id": "vegetarian-noun",
    "word": "vegetarian",
    "baseWord": "vegetable",
    "type": "noun",
    "meaning": "người ăn chay",
    "pronunciation": "/ˌvedʒəˈteriən/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "She has been a strict vegetarian for over five years.",
    "exampleVi": "Cô ấy đã là một người ăn chay nghiêm ngặt trong hơn năm năm.",
    "collocations": ["strict vegetarian", "vegetarian diet", "vegetarian option"],
    "synonyms": ["herbivore"],
    "wordFamily": ["vegetable", "vegetation", "vegetarianism"],
    "day": 57
  },
  {
    "id": "vegan-noun",
    "word": "vegan",
    "baseWord": "vegan",
    "type": "noun",
    "meaning": "người ăn chay thuần (không dùng mọi sản phẩm từ động vật)",
    "pronunciation": "/ˈviːɡən/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "This cafe offers a wide selection of vegan desserts made without dairy.",
    "exampleVi": "Quán cà phê này cung cấp một lựa chọn phong phú các món tráng miệng chay thuần làm không chứa sữa.",
    "collocations": ["strict vegan", "vegan recipe", "vegan option"],
    "synonyms": ["plant-based eater"],
    "wordFamily": ["vegan", "veganism"],
    "day": 57
  },
  {
    "id": "gluten-free-adjective",
    "word": "gluten-free",
    "baseWord": "gluten",
    "type": "adjective",
    "meaning": "không chứa gluten",
    "pronunciation": "/ˌɡluːtn ˈfriː/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We can prepare a gluten-free version of this pasta upon request.",
    "exampleVi": "Chúng tôi có thể chuẩn bị phiên bản không chứa gluten của món mỳ Ý này theo yêu cầu.",
    "collocations": ["gluten-free diet", "gluten-free bread", "gluten-free options"],
    "synonyms": ["gluten-less"],
    "wordFamily": ["gluten"],
    "day": 57
  },
  {
    "id": "grill-verb",
    "word": "grill",
    "baseWord": "grill",
    "type": "verb",
    "meaning": "nướng bằng vỉ, nướng trực tiếp trên lửa",
    "pronunciation": "/ɡrɪl/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The chef will grill the steaks to your preferred level of doneness.",
    "exampleVi": "Đầu bếp sẽ nướng bít tết theo mức độ chín ưa thích của bạn.",
    "collocations": ["grill salmon", "grill meat", "outdoor grill"],
    "synonyms": ["broil", "barbecue"],
    "wordFamily": ["grill", "grilling", "grille"],
    "day": 57
  },
  {
    "id": "roast-verb",
    "word": "roast",
    "baseWord": "roast",
    "type": "verb",
    "meaning": "quay, nướng trong lò (thịt, rau củ)",
    "pronunciation": "/roʊst/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We plan to roast a chicken with herbs and potatoes for dinner.",
    "exampleVi": "Chúng tôi dự định quay một con gà với các loại thảo mộc và khoai tây cho bữa tối.",
    "collocations": ["roast chicken", "roast coffee beans", "roast vegetables"],
    "synonyms": ["bake", "cook in oven"],
    "wordFamily": ["roast", "roasted", "roasting"],
    "day": 57
  },

  # Day 58
  {
    "id": "simmer-verb",
    "word": "simmer",
    "baseWord": "simmer",
    "type": "verb",
    "meaning": "ninh nhỏ lửa, đun sôi nhỏ lửa",
    "pronunciation": "/ˈsɪmər/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 3", "Part 5"],
    "example": "Let the tomato sauce simmer for thirty minutes to enhance the flavor.",
    "exampleVi": "Hãy để sốt cà chua ninh nhỏ lửa trong ba mươi phút để tăng hương vị.",
    "collocations": ["bring to a simmer", "simmer gently", "leave to simmer"],
    "synonyms": ["stew", "boil gently"],
    "wordFamily": ["simmer", "simmering"],
    "day": 58
  },
  {
    "id": "recipe-noun",
    "word": "recipe",
    "baseWord": "recipe",
    "type": "noun",
    "meaning": "công thức nấu ăn",
    "pronunciation": "/ˈresəpi/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "This soup recipe has been passed down through my family for generations.",
    "exampleVi": "Công thức nấu súp này đã được truyền lại qua nhiều thế hệ trong gia đình tôi.",
    "collocations": ["follow a recipe", "secret recipe", "simple recipe"],
    "synonyms": ["formula", "cooking instructions"],
    "wordFamily": ["recipe"],
    "day": 58
  },
  {
    "id": "critique-noun",
    "word": "critique",
    "baseWord": "critic",
    "type": "noun",
    "meaning": "bài phê bình, bài đánh giá chi tiết",
    "pronunciation": "/krɪˈtiːk/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The food writer published a favorable critique of the newly opened bistro.",
    "exampleVi": "Nhà văn viết về ẩm thực đã xuất bản một bài phê bình thuận lợi về quán ăn mới mở.",
    "collocations": ["favorable critique", "constructive critique", "write a critique"],
    "synonyms": ["review", "evaluation", "assessment"],
    "wordFamily": ["critic", "critical", "criticize", "criticism"],
    "day": 58
  },
  {
    "id": "meal voucher-phrase",
    "word": "meal voucher",
    "baseWord": "voucher",
    "type": "phrase",
    "meaning": "phiếu ăn uống, phiếu giảm giá bữa ăn",
    "pronunciation": "/miːl ˈvaʊtʃər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Passengers delayed overnight were given a complimentary meal voucher.",
    "exampleVi": "Các hành khách bị hoãn chuyến qua đêm đã được tặng một phiếu ăn uống miễn phí.",
    "collocations": ["complimentary meal voucher", "redeem a meal voucher", "valid meal voucher"],
    "synonyms": ["food coupon", "dining voucher"],
    "wordFamily": ["meal", "voucher"],
    "day": 58
  },
  {
    "id": "rewards program-phrase",
    "word": "rewards program",
    "baseWord": "ward",
    "type": "phrase",
    "meaning": "chương trình tích điểm thưởng, chương trình khách hàng thân thiết",
    "pronunciation": "/rɪˈwɔːrdz ˈproʊɡræm/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Members of our rewards program earn points for every dollar spent.",
    "exampleVi": "Thành viên trong chương trình thưởng của chúng tôi tích điểm cho mỗi đô la chi tiêu.",
    "collocations": ["join a rewards program", "hotel rewards program", "rewards program benefits"],
    "synonyms": ["loyalty program", "membership program"],
    "wordFamily": ["reward", "program"],
    "day": 58
  },
  {
    "id": "in-room dining-phrase",
    "word": "in-room dining",
    "baseWord": "dine",
    "type": "phrase",
    "meaning": "dịch vụ ăn uống tại phòng khách sạn",
    "pronunciation": "/ɪn ruːm ˈdaɪnɪŋ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "You can order hot meals through the in-room dining service twenty-four hours a day.",
    "exampleVi": "Bạn có thể đặt các bữa ăn nóng thông qua dịch vụ ăn uống tại phòng hai mươi tư giờ một ngày.",
    "collocations": ["order in-room dining", "in-room dining menu", "in-room dining staff"],
    "synonyms": ["room service"],
    "wordFamily": ["dine", "diner", "dining", "room"],
    "day": 58
  },
  {
    "id": "doorman-noun",
    "word": "doorman",
    "baseWord": "doorman",
    "type": "noun",
    "meaning": "nhân viên gác cổng khách sạn",
    "pronunciation": "/ˈdɔːrmæn/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3"],
    "example": "The doorman tipped his hat and opened the taxi door for the guest.",
    "exampleVi": "Nhân viên gác cổng đã chạm mũ chào và mở cửa xe taxi cho khách.",
    "collocations": ["hotel doorman", "greeted by the doorman"],
    "synonyms": ["gatekeeper", "doorkeeper"],
    "wordFamily": ["door", "man"],
    "day": 58
  },
  {
    "id": "luggage rack-phrase",
    "word": "luggage rack",
    "baseWord": "rack",
    "type": "phrase",
    "meaning": "giá để hành lý, kệ để vali",
    "pronunciation": "/ˈlʌɡɪdʒ ræk/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Please place your suitcases on the wooden luggage rack in the closet.",
    "exampleVi": "Vui lòng đặt vali của bạn lên giá để hành lý bằng gỗ trong tủ quần áo.",
    "collocations": ["wooden luggage rack", "hotel room luggage rack"],
    "synonyms": ["baggage rack", "luggage stand"],
    "wordFamily": ["luggage", "rack"],
    "day": 58
  },
  {
    "id": "double room-phrase",
    "word": "double room",
    "baseWord": "room",
    "type": "phrase",
    "meaning": "phòng đôi, phòng dành cho hai người",
    "pronunciation": "/ˈdʌbl ruːm/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We booked a double room with a scenic view of the city harbor.",
    "exampleVi": "Chúng tôi đã đặt một phòng đôi với tầm nhìn tuyệt đẹp ra cảng thành phố.",
    "collocations": ["book a double room", "standard double room", "double room price"],
    "synonyms": ["twin-sharing room"],
    "wordFamily": ["double", "room"],
    "day": 58
  },
  {
    "id": "single room-phrase",
    "word": "single room",
    "baseWord": "room",
    "type": "phrase",
    "meaning": "phòng đơn, phòng dành cho một người",
    "pronunciation": "/ˈsɪŋɡl ruːm/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Since I am traveling alone, a single room will be sufficient for my stay.",
    "exampleVi": "Vì tôi đi du lịch một mình, một phòng đơn sẽ là đủ cho thời gian lưu trú của tôi.",
    "collocations": ["reserve a single room", "cozy single room"],
    "synonyms": ["solo room"],
    "wordFamily": ["single", "room"],
    "day": 58
  },
  {
    "id": "twin bed-phrase",
    "word": "twin bed",
    "baseWord": "bed",
    "type": "phrase",
    "meaning": "giường đơn (trong phòng hai giường đơn)",
    "pronunciation": "/twɪn bed/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The guest room contains two twin beds and a small writing desk.",
    "exampleVi": "Phòng khách chứa hai giường đơn và một bàn viết nhỏ.",
    "collocations": ["room with twin beds", "sleep on a twin bed"],
    "synonyms": ["single bed"],
    "wordFamily": ["twin", "bed"],
    "day": 58
  },
  {
    "id": "king-sized bed-phrase",
    "word": "king-sized bed",
    "baseWord": "bed",
    "type": "phrase",
    "meaning": "giường cỡ lớn, giường lớn nhất",
    "pronunciation": "/kɪŋ saɪzd bed/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The master suite features a luxurious king-sized bed with down pillows.",
    "exampleVi": "Phòng suite chính có một chiếc giường cỡ lớn sang trọng với những chiếc gối lông vũ.",
    "collocations": ["sleep in a king-sized bed", "room with a king-sized bed"],
    "synonyms": ["king bed"],
    "wordFamily": ["king", "size", "bed"],
    "day": 58
  },
  {
    "id": "pillowcase-noun",
    "word": "pillowcase",
    "baseWord": "pillow",
    "type": "noun",
    "meaning": "áo gối, vỏ gối",
    "pronunciation": "/ˈpɪloʊkeɪs/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 1", "Part 5"],
    "example": "Housekeeping replaced the dirty pillowcases with fresh, clean ones.",
    "exampleVi": "Nhân viên dọn phòng đã thay vỏ gối bẩn bằng những cái mới tinh, sạch sẽ.",
    "collocations": ["cotton pillowcase", "change the pillowcase"],
    "synonyms": ["pillow slip"],
    "wordFamily": ["pillow", "case"],
    "day": 58
  },
  {
    "id": "bedsheet-noun",
    "word": "bedsheet",
    "baseWord": "bed",
    "type": "noun",
    "meaning": "ga trải giường, tấm trải giường",
    "pronunciation": "/ˈbedʃiːt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The hotel prides itself on using high-thread-count cotton bedsheets.",
    "exampleVi": "Khách sạn tự hào về việc sử dụng ga trải giường bằng cotton có mật độ sợi cao.",
    "collocations": ["clean bedsheets", "change the bedsheets", "cotton bedsheet"],
    "synonyms": ["sheet", "bed linen"],
    "wordFamily": ["bed", "sheet"],
    "day": 58
  },
  {
    "id": "toiletries-noun",
    "word": "toiletries",
    "baseWord": "toilet",
    "type": "noun",
    "meaning": "đồ dùng cá nhân trong phòng tắm (xà bông, dầu gội...)",
    "pronunciation": "/ˈtɔɪlətriz/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Complimentary toiletries are arranged on the bathroom vanity counter.",
    "exampleVi": "Đồ vệ sinh cá nhân miễn phí được sắp xếp trên quầy phòng tắm.",
    "collocations": ["complimentary toiletries", "provide toiletries", "bathroom toiletries"],
    "synonyms": ["personal hygiene items", "bath amenities"],
    "wordFamily": ["toilet"],
    "day": 58
  },
  {
    "id": "laundry service-phrase",
    "word": "laundry service",
    "baseWord": "launder",
    "type": "phrase",
    "meaning": "dịch vụ giặt ủi",
    "pronunciation": "/ˈlɔːndri ˈsɜːrvɪs/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "If you leave your clothes in the bag, the hotel laundry service will collect them.",
    "exampleVi": "Nếu bạn để quần áo trong túi, dịch vụ giặt ủi của khách sạn sẽ đến thu gom.",
    "collocations": ["hotel laundry service", "use the laundry service", "same-day laundry service"],
    "synonyms": ["laundry facility", "dry cleaning service"],
    "wordFamily": ["launder", "laundromat", "laundry"],
    "day": 58
  },
  {
    "id": "wake-up call-phrase",
    "word": "wake-up call",
    "baseWord": "wake",
    "type": "phrase",
    "meaning": "dịch vụ gọi báo thức",
    "pronunciation": "/ˈweɪk ʌp kɔːl/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "I requested a wake-up call for six-thirty in the morning to catch my flight.",
    "exampleVi": "Tôi đã yêu cầu một cuộc gọi báo thức lúc sáu giờ ba mươi sáng để kịp chuyến bay.",
    "collocations": ["request a wake-up call", "receive a wake-up call", "schedule a wake-up call"],
    "synonyms": ["alarm call"],
    "wordFamily": ["wake", "call"],
    "day": 58
  },
  {
    "id": "hotel shuttle-phrase",
    "word": "hotel shuttle",
    "baseWord": "shuttle",
    "type": "phrase",
    "meaning": "xe buýt đưa đón của khách sạn",
    "pronunciation": "/hoʊˈtel ˈʃʌtl/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The complimentary hotel shuttle runs every half hour to the downtown area.",
    "exampleVi": "Xe đưa đón miễn phí của khách sạn chạy mỗi nửa giờ đến khu vực trung tâm thành phố.",
    "collocations": ["take the hotel shuttle", "hotel shuttle bus", "hotel shuttle schedule"],
    "synonyms": ["hotel bus", "hotel transfer"],
    "wordFamily": ["hotel", "shuttle"],
    "day": 58
  },
  {
    "id": "airport shuttle-phrase",
    "word": "airport shuttle",
    "baseWord": "shuttle",
    "type": "phrase",
    "meaning": "xe đưa đón sân bay",
    "pronunciation": "/ˈerpɔːrt ˈʃʌtl/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Please reserve a seat on the airport shuttle for Friday morning.",
    "exampleVi": "Vui lòng đặt trước một chỗ trên xe đưa đón sân bay vào sáng thứ Sáu.",
    "collocations": ["complimentary airport shuttle", "airport shuttle service"],
    "synonyms": ["airport bus", "airport transfer shuttle"],
    "wordFamily": ["air", "port", "shuttle"],
    "day": 58
  },
  {
    "id": "overbook-verb",
    "word": "overbook",
    "baseWord": "book",
    "type": "verb",
    "meaning": "đặt chỗ quá số lượng cho phép",
    "pronunciation": "/ˌoʊvərˈbʊk/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Airlines and hotels sometimes overbook to compensate for potential cancellations.",
    "exampleVi": "Các hãng hàng không và khách sạn đôi khi đặt chỗ quá số lượng để bù đắp cho những ca hủy phòng tiềm năng.",
    "collocations": ["overbook a flight", "overbooked hotel"],
    "synonyms": ["sell out excess"],
    "wordFamily": ["book", "booking", "overbooked"],
    "day": 58
  },

  # Day 59
  {
    "id": "fully booked-adjective",
    "word": "fully booked",
    "baseWord": "book",
    "type": "adjective",
    "meaning": "đã được đặt kín chỗ, không còn chỗ trống",
    "pronunciation": "/ˈfʊli ˈbʊkt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We had to choose a different hotel because our first choice was fully booked.",
    "exampleVi": "Chúng tôi phải chọn một khách sạn khác vì lựa chọn đầu tiên đã kín phòng.",
    "collocations": ["fully booked hotel", "restaurant is fully booked"],
    "synonyms": ["booked solid", "filled to capacity"],
    "wordFamily": ["book", "booked"],
    "day": 59
  },
  {
    "id": "no-show-noun",
    "word": "no-show",
    "baseWord": "show",
    "type": "noun",
    "meaning": "khách đặt chỗ nhưng không đến và không báo trước",
    "pronunciation": "/ˈnoʊ ʃoʊ/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The restaurant policy states that no-shows will lose their security deposit.",
    "exampleVi": "Chính sách của nhà hàng quy định rằng những khách đặt nhưng không đến sẽ mất tiền đặt cọc.",
    "collocations": ["no-show fee", "avoid no-shows", "rate of no-shows"],
    "synonyms": ["absentee", "non-attendee"],
    "wordFamily": ["show"],
    "day": 59
  },
  {
    "id": "cancellation fee-phrase",
    "word": "cancellation fee",
    "baseWord": "cancel",
    "type": "phrase",
    "meaning": "phí hủy đặt phòng/chỗ",
    "pronunciation": "/ˌkænsəˈleɪʃn fiː/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "If you cancel within twenty-four hours of your stay, you will be charged a cancellation fee.",
    "exampleVi": "Nếu bạn hủy trong vòng hai mươi tư giờ trước kỳ lưu trú, bạn sẽ bị tính phí hủy phòng.",
    "collocations": ["pay a cancellation fee", "subject to a cancellation fee"],
    "synonyms": ["refund penalty"],
    "wordFamily": ["cancel", "cancellation", "fee"],
    "day": 59
  },
  {
    "id": "group booking-phrase",
    "word": "group booking",
    "baseWord": "book",
    "type": "phrase",
    "meaning": "đặt chỗ theo nhóm/đoàn",
    "pronunciation": "/ɡruːp ˈbʊkɪŋ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We qualify for a discounted room rate because of our group booking.",
    "exampleVi": "Chúng tôi đủ điều kiện nhận giá phòng giảm giá vì chúng tôi đặt phòng theo đoàn.",
    "collocations": ["make a group booking", "group booking rates", "group booking policy"],
    "synonyms": ["block reservation", "bulk booking"],
    "wordFamily": ["group", "book", "booking"],
    "day": 59
  },
  {
    "id": "peak season-phrase",
    "word": "peak season",
    "baseWord": "season",
    "type": "phrase",
    "meaning": "mùa cao điểm du lịch",
    "pronunciation": "/piːk ˈsiːzn/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Flight and accommodation prices are significantly higher during the peak season.",
    "exampleVi": "Giá vé máy bay và phòng ở cao hơn đáng kể trong mùa du lịch cao điểm.",
    "collocations": ["during peak season", "peak season travel", "peak season rates"],
    "synonyms": ["high season", "busy season"],
    "wordFamily": ["peak", "season", "seasonal"],
    "day": 59
  },
  {
    "id": "off-peak-adjective",
    "word": "off-peak",
    "baseWord": "peak",
    "type": "adjective",
    "meaning": "ngoài giờ cao điểm, mùa thấp điểm",
    "pronunciation": "/ˌɔːf ˈpiːk/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Traveling during off-peak times can help you save on train tickets.",
    "exampleVi": "Đi du lịch vào các thời điểm ngoài giờ cao điểm có thể giúp bạn tiết kiệm tiền vé tàu.",
    "collocations": ["off-peak hours", "off-peak season", "off-peak travel"],
    "synonyms": ["low-season", "shoulder season"],
    "wordFamily": ["peak", "seasonal"],
    "day": 59
  },
  {
    "id": "tourist attraction-phrase",
    "word": "tourist attraction",
    "baseWord": "attract",
    "type": "phrase",
    "meaning": "địa điểm thu hút khách du lịch",
    "pronunciation": "/ˈtʊrɪst əˈtrækʃn/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The historic cathedral is the main tourist attraction in the region.",
    "exampleVi": "Nhà thờ lịch sử là điểm thu hút khách du lịch chính trong vùng.",
    "collocations": ["popular tourist attraction", "famous tourist attraction"],
    "synonyms": ["sight", "tourist spot", "landmark"],
    "wordFamily": ["tour", "tourist", "attract", "attraction"],
    "day": 59
  },
  {
    "id": "sightseeing-noun",
    "word": "sightseeing",
    "baseWord": "sight",
    "type": "noun",
    "meaning": "hoạt động tham quan, ngắm cảnh",
    "pronunciation": "/ˈsaɪtsiːɪŋ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We plan to do some sightseeing around the historic district tomorrow.",
    "exampleVi": "Chúng tôi dự định đi tham quan xung quanh khu di tích lịch sử vào ngày mai.",
    "collocations": ["go sightseeing", "sightseeing tour", "sightseeing bus"],
    "synonyms": ["tourism", "excursion"],
    "wordFamily": ["sight", "see"],
    "day": 59
  },
  {
    "id": "guided tour-phrase",
    "word": "guided tour",
    "baseWord": "tour",
    "type": "phrase",
    "meaning": "chuyến tham quan có hướng dẫn viên",
    "pronunciation": "/ˈɡaɪdɪd tʊr/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Taking a guided tour of the museum provides a more informative experience.",
    "exampleVi": "Tham gia một chuyến tham quan bảo tàng có hướng dẫn viên sẽ đem lại trải nghiệm nhiều thông tin hơn.",
    "collocations": ["join a guided tour", "guided tour of the palace", "daily guided tours"],
    "synonyms": ["escorted tour"],
    "wordFamily": ["guide", "tour", "tourism"],
    "day": 59
  },
  {
    "id": "local guide-phrase",
    "word": "local guide",
    "baseWord": "guide",
    "type": "phrase",
    "meaning": "hướng dẫn viên địa phương",
    "pronunciation": "/ˈloʊkl ɡaɪd/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We hired a local guide to show us the hidden spots of the island.",
    "exampleVi": "Chúng tôi đã thuê một hướng dẫn viên địa phương để chỉ cho chúng tôi những địa điểm ẩn giấu của hòn đảo.",
    "collocations": ["hire a local guide", "knowledgeable local guide"],
    "synonyms": ["native guide"],
    "wordFamily": ["local", "locality", "guide", "guidance"],
    "day": 59
  },
  {
    "id": "souvenir-noun",
    "word": "souvenir",
    "baseWord": "souvenir",
    "type": "noun",
    "meaning": "đồ lưu niệm, quà lưu niệm",
    "pronunciation": "/ˌsuːvəˈnɪr/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "I bought a small wooden carvings model as a souvenir of my trip to Vietnam.",
    "exampleVi": "Tôi đã mua một mô hình chạm khắc bằng gỗ nhỏ làm kỷ niệm cho chuyến đi Việt Nam.",
    "collocations": ["buy a souvenir", "souvenir shop", "popular souvenir"],
    "synonyms": ["keepsake", "memento", "token"],
    "wordFamily": ["souvenir"],
    "day": 59
  },
  {
    "id": "hospitality industry-phrase",
    "word": "hospitality industry",
    "baseWord": "hospitality",
    "type": "phrase",
    "meaning": "ngành công nghiệp dịch vụ khách sạn - nhà hàng",
    "pronunciation": "/ˌhɑːspɪˈtæləti ˈɪndəstri/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 5", "Part 7"],
    "example": "Customer satisfaction is the top priority in the hospitality industry.",
    "exampleVi": "Sự hài lòng của khách hàng là ưu tiên hàng đầu trong ngành dịch vụ khách sạn - nhà hàng.",
    "collocations": ["work in the hospitality industry", "hospitality industry trends"],
    "synonyms": ["service sector", "hotel sector"],
    "wordFamily": ["hospitality", "hospitable", "industry", "industrial"],
    "day": 59
  },
  {
    "id": "guest lodge-phrase",
    "word": "guest lodge",
    "baseWord": "lodge",
    "type": "phrase",
    "meaning": "nhà nghỉ dành cho khách, nhà khách",
    "pronunciation": "/ɡest lɑːdʒ/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 5", "Part 7"],
    "example": "The guest lodge provides rustic but comfortable rooms near the national park.",
    "exampleVi": "Nhà nghỉ dành cho khách cung cấp những phòng mộc mạc nhưng thoải mái gần công viên quốc gia.",
    "collocations": ["mountain guest lodge", "stay at a guest lodge"],
    "synonyms": ["guesthouse", "guest cabin", "inn"],
    "wordFamily": ["guest", "lodge", "lodging"],
    "day": 59
  },
  {
    "id": "motor lodge-phrase",
    "word": "motor lodge",
    "baseWord": "lodge",
    "type": "phrase",
    "meaning": "nhà nghỉ dọc đường (cho người đi xe ô tô)",
    "pronunciation": "/ˈmoʊtər lɑːdʒ/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "We stayed at a quiet motor lodge off the highway for one night.",
    "exampleVi": "Chúng tôi đã nghỉ tại một nhà nghỉ dọc đường yên tĩnh cách xa xa lộ trong một đêm.",
    "collocations": ["budget motor lodge", "roadside motor lodge"],
    "synonyms": ["motel", "roadside inn"],
    "wordFamily": ["motor", "lodge", "lodging"],
    "day": 59
  },
  {
    "id": "resort hotel-phrase",
    "word": "resort hotel",
    "baseWord": "hotel",
    "type": "phrase",
    "meaning": "khách sạn nghỉ dưỡng",
    "pronunciation": "/rɪˈzɔːrt hoʊˈtel/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The beachside resort hotel offers full-service spa treatments and private beach access.",
    "exampleVi": "Khách sạn nghỉ dưỡng bên bờ biển cung cấp các liệu trình spa trọn gói và lối ra bãi biển riêng.",
    "collocations": ["luxury resort hotel", "resort hotel manager", "beachfront resort hotel"],
    "synonyms": ["vacation resort", "holiday resort"],
    "wordFamily": ["resort", "hotel"],
    "day": 59
  },
  {
    "id": "guest house-phrase",
    "word": "guest house",
    "baseWord": "house",
    "type": "phrase",
    "meaning": "nhà khách, nhà nghỉ gia đình",
    "pronunciation": "/ɡest haʊs/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "They decided to stay in a cozy guest house rather than a large hotel chain.",
    "exampleVi": "Họ quyết định ở trong một nhà khách ấm cúng hơn là một chuỗi khách sạn lớn.",
    "collocations": ["family-run guest house", "stay in a guest house"],
    "synonyms": ["pension", "boarding house"],
    "wordFamily": ["guest", "house"],
    "day": 59
  },
  {
    "id": "bed and breakfast-phrase",
    "word": "bed and breakfast",
    "baseWord": "breakfast",
    "type": "phrase",
    "meaning": "dịch vụ phòng ngủ kèm bữa sáng (thường là nhà nghỉ nhỏ tư nhân)",
    "pronunciation": "/bed ənd ˈbrekfəst/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We booked a weekend stay at a charming bed and breakfast in the countryside.",
    "exampleVi": "Chúng tôi đã đặt phòng nghỉ cuối tuần tại một nhà nghỉ giường ngủ kèm bữa sáng duyên dáng ở nông thôn.",
    "collocations": ["cozy bed and breakfast", "run a bed and breakfast"],
    "synonyms": ["B&B", "guesthouse"],
    "wordFamily": ["bed", "breakfast"],
    "day": 59
  },
  {
    "id": "check-in desk-phrase",
    "word": "check-in desk",
    "baseWord": "desk",
    "type": "phrase",
    "meaning": "quầy làm thủ tục nhận phòng / làm thủ tục lên máy bay",
    "pronunciation": "/ˈtʃek ɪn desk/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "A line of travelers had already formed at the airline check-in desk.",
    "exampleVi": "Một dòng du khách đã hình thành tại quầy làm thủ tục của hãng hàng không.",
    "collocations": ["go to the check-in desk", "hotel check-in desk", "check-in desk agent"],
    "synonyms": ["reception desk", "front desk"],
    "wordFamily": ["check", "in", "desk"],
    "day": 59
  },
  {
    "id": "keycard-noun",
    "word": "keycard",
    "baseWord": "key",
    "type": "noun",
    "meaning": "thẻ khóa từ mở phòng khách sạn",
    "pronunciation": "/ˈkiːkɑːrd/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "You need to swipe your electronic keycard to activate the elevator.",
    "exampleVi": "Bạn cần quẹt thẻ khóa từ điện tử của mình để kích hoạt thang máy.",
    "collocations": ["hotel keycard", "swipe a keycard", "lose a keycard"],
    "synonyms": ["electronic key", "smart card"],
    "wordFamily": ["key", "card"],
    "day": 59
  },
  {
    "id": "baggage claim-phrase",
    "word": "baggage claim",
    "baseWord": "claim",
    "type": "phrase",
    "meaning": "khu vực nhận lại hành lý (tại sân bay)",
    "pronunciation": "/ˈbæɡɪdʒ kleɪm/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We headed straight to the baggage claim area after exiting the aircraft.",
    "exampleVi": "Chúng tôi đi thẳng đến khu vực nhận hành lý sau khi rời máy bay.",
    "collocations": ["baggage claim area", "wait at baggage claim", "baggage claim ticket"],
    "synonyms": ["luggage reclaim"],
    "wordFamily": ["bag", "baggage", "claim", "claimant"],
    "day": 59
  },

  # Day 60
  {
    "id": "porter-noun",
    "word": "porter",
    "baseWord": "porter",
    "type": "noun",
    "meaning": "nhân viên khuân vác hành lý (ga tàu, khách sạn)",
    "pronunciation": "/ˈpɔːrtər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "The train station porter loaded our heavy luggage onto a cart.",
    "exampleVi": "Nhân viên khuân vác ở ga tàu đã chất hành lý nặng của chúng tôi lên một chiếc xe đẩy.",
    "collocations": ["railway porter", "hotel porter", "tip the porter"],
    "synonyms": ["baggage handler", "bellhop"],
    "wordFamily": ["port", "porterage"],
    "day": 60
  },
  {
    "id": "cloakroom-noun",
    "word": "cloakroom",
    "baseWord": "cloak",
    "type": "noun",
    "meaning": "phòng gửi áo khoác, phòng để mũ nón hành lý",
    "pronunciation": "/ˈkloʊkruːm/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "You can leave your heavy coats in the hotel cloakroom during the dinner.",
    "exampleVi": "Bạn có thể gửi những chiếc áo khoác dày của mình trong phòng gửi đồ của khách sạn trong suốt bữa tối.",
    "collocations": ["leave coats in the cloakroom", "cloakroom attendant", "cloakroom ticket"],
    "synonyms": ["coatroom", "checkroom"],
    "wordFamily": ["cloak", "room"],
    "day": 60
  },
  {
    "id": "lost and found-noun",
    "word": "lost and found",
    "baseWord": "find",
    "type": "noun",
    "meaning": "văn phòng thất lạc và tìm thấy đồ",
    "pronunciation": "/ˌlɔːst ənd ˈfaʊnd/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "I went to the lost and found to report that I had left my tablet on the train.",
    "exampleVi": "Tôi đã đến văn phòng thất lạc đồ để báo rằng tôi đã bỏ quên máy tính bảng trên tàu.",
    "collocations": ["go to the lost and found", "lost and found office", "lost and found box"],
    "synonyms": ["lost property office"],
    "wordFamily": ["lose", "lost", "find", "found"],
    "day": 60
  },
  {
    "id": "main course-phrase",
    "word": "main course",
    "baseWord": "course",
    "type": "phrase",
    "meaning": "món ăn chính trong bữa ăn",
    "pronunciation": "/meɪn kɔːrs/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "For the main course, I ordered the grilled sea bass with asparagus.",
    "exampleVi": "Đối với món chính, tôi đã gọi món cá vược nướng kèm măng tây.",
    "collocations": ["serve the main course", "main course options", "delicious main course"],
    "synonyms": ["entrée", "main dish"],
    "wordFamily": ["main", "course"],
    "day": 60
  },
  {
    "id": "appetizer-noun",
    "word": "appetizer",
    "baseWord": "appetite",
    "type": "noun",
    "meaning": "món khai vị",
    "pronunciation": "/ˈæpɪtaɪzər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We shared an appetizer of stuffed mushrooms before our main dishes arrived.",
    "exampleVi": "Chúng tôi đã chia sẻ món khai vị nấm nhồi trước khi các món chính của chúng tôi được mang ra.",
    "collocations": ["hot appetizer", "order an appetizer", "appetizer platter"],
    "synonyms": ["starter", "hors d'oeuvre"],
    "wordFamily": ["appetite", "appetizing"],
    "day": 60
  },
  {
    "id": "dessert-noun",
    "word": "dessert",
    "baseWord": "dessert",
    "type": "noun",
    "meaning": "món tráng miệng",
    "pronunciation": "/dɪˈzɜːrt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The waiter brought a dessert menu featuring chocolate lava cake and fruit tarts.",
    "exampleVi": "Người phục vụ mang ra thực đơn tráng miệng gồm bánh kem sô-cô-la tan chảy và bánh tart trái cây.",
    "collocations": ["order dessert", "dessert menu", "delicious dessert"],
    "synonyms": ["sweet course", "afters"],
    "wordFamily": ["dessert"],
    "day": 60
  },
  {
    "id": "beverage-noun",
    "word": "beverage",
    "baseWord": "beverage",
    "type": "noun",
    "meaning": "đồ uống, thức uống (nói chung)",
    "pronunciation": "/ˈbevərɪdʒ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Hot and cold beverages are available for purchase in the hotel lobby.",
    "exampleVi": "Đồ uống nóng và lạnh luôn sẵn sàng để mua tại sảnh khách sạn.",
    "collocations": ["alcoholic beverage", "non-alcoholic beverage", "hot beverage"],
    "synonyms": ["drink", "refreshment"],
    "wordFamily": ["beverage"],
    "day": 60
  },
  {
    "id": "soft drink-phrase",
    "word": "soft drink",
    "baseWord": "drink",
    "type": "phrase",
    "meaning": "nước ngọt, nước giải khát không chứa cồn",
    "pronunciation": "/sɔːft drɪŋk/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "I prefer a sugar-free soft drink over fruit juice.",
    "exampleVi": "Tôi thích một loại nước ngọt không đường hơn là nước ép trái cây.",
    "collocations": ["order a soft drink", "can of soft drink", "soft drink dispenser"],
    "synonyms": ["soda", "carbonated beverage"],
    "wordFamily": ["soft", "drink", "drinking"],
    "day": 60
  },
  {
    "id": "sparkling water-phrase",
    "word": "sparkling water",
    "baseWord": "water",
    "type": "phrase",
    "meaning": "nước khoáng có ga",
    "pronunciation": "/ˈspɑːrklɪŋ ˈwɔːtər/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The server brought a bottle of sparkling water with a slice of lemon.",
    "exampleVi": "Người phục vụ mang ra một chai nước khoáng có ga kèm theo một lát chanh.",
    "collocations": ["bottle of sparkling water", "order sparkling water"],
    "synonyms": ["carbonated water", "fizzy water", "soda water"],
    "wordFamily": ["sparkle", "sparkling", "water"],
    "day": 60
  },
  {
    "id": "house wine-phrase",
    "word": "house wine",
    "baseWord": "wine",
    "type": "phrase",
    "meaning": "rượu vang đặc trưng giá rẻ của nhà hàng",
    "pronunciation": "/haʊs waɪn/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5"],
    "example": "We ordered a carafe of the house wine to accompany our meal.",
    "exampleVi": "Chúng tôi đã gọi một bình rượu vang đặc trưng của nhà hàng để dùng kèm với bữa ăn.",
    "collocations": ["carafe of house wine", "red house wine", "white house wine"],
    "synonyms": ["table wine"],
    "wordFamily": ["house", "wine"],
    "day": 60
  },
  {
    "id": "dining room-phrase",
    "word": "dining room",
    "baseWord": "room",
    "type": "phrase",
    "meaning": "phòng ăn (trong nhà hoặc nhà hàng)",
    "pronunciation": "/ˈdaɪnɪŋ ruːm/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 1", "Part 3", "Part 5"],
    "example": "Guests are gathered in the main dining room for the breakfast buffet.",
    "exampleVi": "Khách khứa tập trung tại phòng ăn chính để dùng bữa tiệc đứng buổi sáng.",
    "collocations": ["main dining room", "spacious dining room", "dining room table"],
    "synonyms": ["refectory", "mess hall"],
    "wordFamily": ["dine", "dining", "room"],
    "day": 60
  },
  {
    "id": "kitchen staff-phrase",
    "word": "kitchen staff",
    "baseWord": "staff",
    "type": "phrase",
    "meaning": "nhân viên nhà bếp",
    "pronunciation": "/ˈkɪtʃɪn stæf/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The kitchen staff worked quickly to prepare the meals for the banquet.",
    "exampleVi": "Nhân viên nhà bếp đã làm việc nhanh chóng để chuẩn bị các bữa ăn cho bữa tiệc yến.",
    "collocations": ["hire kitchen staff", "experienced kitchen staff"],
    "synonyms": ["kitchen crew", "kitchen workers"],
    "wordFamily": ["kitchen", "staff"],
    "day": 60
  },
  {
    "id": "head chef-phrase",
    "word": "head chef",
    "baseWord": "chef",
    "type": "phrase",
    "meaning": "bếp trưởng",
    "pronunciation": "/hed ʃef/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The head chef personally inspects each dish before it leaves the kitchen.",
    "exampleVi": "Bếp trưởng đích thân kiểm tra từng món ăn trước khi nó rời khỏi nhà bếp.",
    "collocations": ["meet the head chef", "appointed as head chef"],
    "synonyms": ["executive chef", "master chef"],
    "wordFamily": ["head", "chef"],
    "day": 60
  },
  {
    "id": "sous chef-phrase",
    "word": "sous chef",
    "baseWord": "chef",
    "type": "phrase",
    "meaning": "bếp phó (người đứng thứ hai sau bếp trưởng)",
    "pronunciation": "/ˈsuː ʃef/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The sous chef is responsible for managing the kitchen staff during the busy shift.",
    "exampleVi": "Bếp phó chịu trách nhiệm quản lý nhân viên bếp trong ca làm việc bận rộn.",
    "collocations": ["work as a sous chef", "experienced sous chef"],
    "synonyms": ["second chef", "assistant chef"],
    "wordFamily": ["chef"],
    "day": 60
  },
  {
    "id": "table reservation-phrase",
    "word": "table reservation",
    "baseWord": "reserve",
    "type": "phrase",
    "meaning": "sự đặt bàn ăn trước ở nhà hàng",
    "pronunciation": "/ˈteɪbl ˌrezərˈveɪʃn/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We have a table reservation under the name of Mr. Miller for eight o'clock.",
    "exampleVi": "Chúng tôi có một sự đặt bàn dưới tên của ông Miller vào lúc tám giờ.",
    "collocations": ["make a table reservation", "confirm a table reservation"],
    "synonyms": ["restaurant booking", "dinner reservation"],
    "wordFamily": ["table", "reserve", "reservation"],
    "day": 60
  },
  {
    "id": "corkage fee-phrase",
    "word": "corkage fee",
    "baseWord": "fee",
    "type": "phrase",
    "meaning": "phí mang rượu ngoài vào nhà hàng, phí mở chai",
    "pronunciation": "/ˈkɔːrkɪdʒ fiː/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The restaurant charges a twenty-dollar corkage fee if you bring your own wine.",
    "exampleVi": "Nhà hàng tính phí mang rượu ngoài hai mươi đô la nếu bạn tự mang rượu vang của riêng mình.",
    "collocations": ["charge a corkage fee", "pay a corkage fee", "corkage fee policy"],
    "synonyms": ["bottle opening fee"],
    "wordFamily": ["cork", "fee"],
    "day": 60
  },
  {
    "id": "signature dish-phrase",
    "word": "signature dish",
    "baseWord": "sign",
    "type": "phrase",
    "meaning": "món ăn mang thương hiệu, món ăn đặc trưng của đầu bếp/nhà hàng",
    "pronunciation": "/ˈsɪɡnətʃər dɪʃ/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The chef's signature dish is pan-seared scallops with truffle oil.",
    "exampleVi": "Món ăn đặc trưng của đầu bếp là sò điệp áp chảo với dầu nấm truffle.",
    "collocations": ["taste the signature dish", "signature dish of the restaurant"],
    "synonyms": ["specialty", "house specialty"],
    "wordFamily": ["sign", "signature", "dish"],
    "day": 60
  },
  {
    "id": "wine list-phrase",
    "word": "wine list",
    "baseWord": "list",
    "type": "phrase",
    "meaning": "danh sách các loại rượu vang",
    "pronunciation": "/waɪn lɪst/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Our sommelier would be happy to help you choose a bottle from the wine list.",
    "exampleVi": "Chuyên gia thử rượu của chúng tôi rất vui lòng giúp bạn chọn một chai từ danh sách rượu vang.",
    "collocations": ["extensive wine list", "study the wine list", "choose from the wine list"],
    "synonyms": ["wine menu"],
    "wordFamily": ["wine", "list"],
    "day": 60
  },
  {
    "id": "tasting menu-phrase",
    "word": "tasting menu",
    "baseWord": "taste",
    "type": "phrase",
    "meaning": "thực đơn nếm thử (thực đơn gồm nhiều món nhỏ đặc sắc của nhà hàng)",
    "pronunciation": "/ˈteɪstɪŋ ˈmenjuː/",
    "topic": "Hospitality & Dining",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "We opted for the seven-course tasting menu to experience the chef's full range of skills.",
    "exampleVi": "Chúng tôi đã chọn thực đơn nếm thử bảy món để trải nghiệm đầy đủ các kỹ năng của đầu bếp.",
    "collocations": ["seven-course tasting menu", "offer a tasting menu"],
    "synonyms": ["degustation menu", "sample menu"],
    "wordFamily": ["taste", "tasty", "tasting", "menu"],
    "day": 60
  },
  {
    "id": "a la carte-adjective",
    "word": "a la carte",
    "baseWord": "carte",
    "type": "adjective",
    "meaning": "(gọi món) theo thực đơn riêng lẻ, gọi món lẻ",
    "pronunciation": "/ˌæ lɑː ˈkɑːrt/",
    "topic": "Hospitality & Dining",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "You can order from the a la carte menu or choose the set dinner option.",
    "exampleVi": "Bạn có thể gọi từ thực đơn món lẻ hoặc chọn phương án bữa tối cố định.",
    "collocations": ["a la carte menu", "dine a la carte", "order a la carte"],
    "synonyms": ["individual dish ordering"],
    "wordFamily": ["carte"],
    "day": 60
  }
]

# Write to file
output_path = r"g:\InLit\scripts\vocab-batches\vocab_day_056_060.json"
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Successfully generated {len(data)} entries for Days 56-60.")
