import json
import os

data = [
  # Day 21
  {
    "id": "commute-verb",
    "word": "commute",
    "baseWord": "commute",
    "type": "verb",
    "meaning": "đi lại thường nhật (giữa nhà và nơi làm việc)",
    "pronunciation": "/kəˈmjuːt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Many employees commute to work by train every day.",
    "exampleVi": "Nhiều nhân viên đi làm bằng tàu hỏa mỗi ngày.",
    "collocations": ["commute to work", "commute daily", "commute by train"],
    "synonyms": ["travel"],
    "wordFamily": ["commuter", "commuting"],
    "day": 21
  },
  {
    "id": "commuter-noun",
    "word": "commuter",
    "baseWord": "commute",
    "type": "noun",
    "meaning": "người đi làm bằng phương tiện công cộng hàng ngày",
    "pronunciation": "/kəˈmjuːtər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 4", "Part 5", "Part 7"],
    "example": "The commuters complained about the delay in the train service.",
    "exampleVi": "Những người đi lại hàng ngày đã phàn nàn về sự chậm trễ của dịch vụ tàu hỏa.",
    "collocations": ["daily commuter", "commuter train", "commuter route"],
    "synonyms": ["passenger"],
    "wordFamily": ["commute", "commuting"],
    "day": 21
  },
  {
    "id": "shuttle-noun",
    "word": "shuttle",
    "baseWord": "shuttle",
    "type": "noun",
    "meaning": "xe đưa đón, phương tiện chạy tuyến đường ngắn cố định",
    "pronunciation": "/ˈʃʌtl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The hotel provides a free shuttle to the airport.",
    "exampleVi": "Khách sạn cung cấp dịch vụ xe đưa đón miễn phí đến sân bay.",
    "collocations": ["airport shuttle", "shuttle bus", "shuttle service"],
    "synonyms": ["transport"],
    "wordFamily": [],
    "day": 21
  },
  {
    "id": "fare-noun",
    "word": "fare",
    "baseWord": "fare",
    "type": "noun",
    "meaning": "tiền vé, cước phí di chuyển",
    "pronunciation": "/fer/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Bus fares have increased significantly this year.",
    "exampleVi": "Giá vé xe buýt đã tăng đáng kể trong năm nay.",
    "collocations": ["bus fare", "train fare", "air fare"],
    "synonyms": ["price", "cost", "charge"],
    "wordFamily": [],
    "day": 21
  },
  {
    "id": "transit-noun",
    "word": "transit",
    "baseWord": "transit",
    "type": "noun",
    "meaning": "sự đi qua, sự quá cảnh, hệ thống giao thông công cộng",
    "pronunciation": "/ˈtrænzɪt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 4", "Part 5", "Part 7"],
    "example": "The goods were damaged while in transit.",
    "exampleVi": "Hàng hóa đã bị hư hại khi đang trên đường vận chuyển.",
    "collocations": ["in transit", "mass transit", "transit system"],
    "synonyms": ["transportation", "passage"],
    "wordFamily": ["transition", "transitory"],
    "day": 21
  },
  {
    "id": "passenger-noun",
    "word": "passenger",
    "baseWord": "passenger",
    "type": "noun",
    "meaning": "hành khách",
    "pronunciation": "/ˈpæsɪndʒər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 4", "Part 7"],
    "example": "Passengers are requested to remain seated during takeoff.",
    "exampleVi": "Hành khách được yêu cầu giữ nguyên vị trí ngồi trong lúc cất cánh.",
    "collocations": ["airline passenger", "passenger train", "passenger seat"],
    "synonyms": ["traveler", "commuter"],
    "wordFamily": [],
    "day": 21
  },
  {
    "id": "route-noun",
    "word": "route",
    "baseWord": "route",
    "type": "noun",
    "meaning": "lộ trình, tuyến đường",
    "pronunciation": "/ruːt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The driver took a different route to avoid the traffic jam.",
    "exampleVi": "Tài xế đã đi một tuyến đường khác để tránh kẹt xe.",
    "collocations": ["bus route", "scenic route", "direct route"],
    "synonyms": ["path", "way", "course"],
    "wordFamily": ["reroute"],
    "day": 21
  },
  {
    "id": "destination-noun",
    "word": "destination",
    "baseWord": "destine",
    "type": "noun",
    "meaning": "điểm đến, đích đến",
    "pronunciation": "/ˌdestɪˈneɪʃn/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We reached our destination after a ten-hour drive.",
    "exampleVi": "Chúng tôi đã đến đích sau mười giờ lái xe.",
    "collocations": ["popular destination", "final destination", "holiday destination"],
    "synonyms": ["goal", "target"],
    "wordFamily": ["destined", "destiny"],
    "day": 21
  },
  {
    "id": "departure-noun",
    "word": "departure",
    "baseWord": "depart",
    "type": "noun",
    "meaning": "sự khởi hành, giờ khởi hành",
    "pronunciation": "/dɪˈpɑːrtʃər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The departure of flight VN123 has been delayed by two hours.",
    "exampleVi": "Giờ khởi hành của chuyến bay VN123 đã bị hoãn lại hai tiếng.",
    "collocations": ["departure lounge", "departure time", "scheduled departure"],
    "synonyms": ["leaving", "exit"],
    "wordFamily": ["depart", "departed"],
    "day": 21
  },
  {
    "id": "arrival-noun",
    "word": "arrival",
    "baseWord": "arrive",
    "type": "noun",
    "meaning": "sự đến nơi, giờ đến nơi",
    "pronunciation": "/əˈraɪvl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Please check the screens for the latest arrival times.",
    "exampleVi": "Vui lòng kiểm tra màn hình để biết thời gian đến mới nhất.",
    "collocations": ["arrival hall", "arrival time", "scheduled arrival"],
    "synonyms": ["advent", "coming"],
    "wordFamily": ["arrive"],
    "day": 21
  },
  {
    "id": "delay-verb",
    "word": "delay",
    "baseWord": "delay",
    "type": "verb",
    "meaning": "hoãn lại, làm trễ nải",
    "pronunciation": "/dɪˈleɪ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 6"],
    "example": "Our flight was delayed due to heavy snowfall.",
    "exampleVi": "Chuyến bay của chúng tôi đã bị hoãn do tuyết rơi dày đặc.",
    "collocations": ["delay a flight", "delay a decision", "unavoidably delayed"],
    "synonyms": ["postpone", "defer"],
    "wordFamily": ["delayed"],
    "day": 21
  },
  {
    "id": "cancellation-noun",
    "word": "cancellation",
    "baseWord": "cancel",
    "type": "noun",
    "meaning": "sự hủy bỏ (lịch trình, đặt chỗ)",
    "pronunciation": "/ˌkænsəˈleɪʃn/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We apologize for the cancellation of today's train service.",
    "exampleVi": "Chúng tôi xin lỗi vì sự hủy bỏ dịch vụ tàu hỏa hôm nay.",
    "collocations": ["cancellation policy", "last-minute cancellation", "flight cancellation"],
    "synonyms": ["calling off", "annulment"],
    "wordFamily": ["cancel", "cancelled"],
    "day": 21
  },
  {
    "id": "layover-noun",
    "word": "layover",
    "baseWord": "layover",
    "type": "noun",
    "meaning": "điểm dừng chân, thời gian chờ chuyến bay tiếp theo",
    "pronunciation": "/ˈleɪoʊvər/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 7"],
    "example": "I had a four-hour layover in Tokyo before connecting to Seoul.",
    "exampleVi": "Tôi đã có bốn tiếng chờ ở Tokyo trước khi nối chuyến đi Seoul.",
    "collocations": ["brief layover", "overnight layover", "layover flight"],
    "synonyms": ["stopover"],
    "wordFamily": [],
    "day": 21
  },
  {
    "id": "boarding-noun",
    "word": "boarding",
    "baseWord": "board",
    "type": "noun",
    "meaning": "việc lên tàu, xe, máy bay",
    "pronunciation": "/ˈbɔːrdɪŋ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 4"],
    "example": "Boarding will begin at gate 15 in approximately ten minutes.",
    "exampleVi": "Việc lên máy bay sẽ bắt đầu tại cổng số 15 trong khoảng mười phút nữa.",
    "collocations": ["boarding pass", "boarding gate", "boarding time"],
    "synonyms": ["embarkation"],
    "wordFamily": ["board", "boarder"],
    "day": 21
  },
  {
    "id": "terminal-noun",
    "word": "terminal",
    "baseWord": "term",
    "type": "noun",
    "meaning": "nhà ga (sân bay, bến tàu, xe)",
    "pronunciation": "/ˈtɜːrmɪnl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 4", "Part 7"],
    "example": "Flights to Europe depart from Terminal 2.",
    "exampleVi": "Các chuyến bay đến Châu Âu khởi hành từ Nhà ga số 2.",
    "collocations": ["airport terminal", "passenger terminal", "cargo terminal"],
    "synonyms": ["station", "depot"],
    "wordFamily": ["terminate", "termination"],
    "day": 21
  },
  {
    "id": "luggage-noun",
    "word": "luggage",
    "baseWord": "luggage",
    "type": "noun",
    "meaning": "hành lý (nói chung)",
    "pronunciation": "/ˈlʌɡɪdʒ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Please do not leave your luggage unattended at any time.",
    "exampleVi": "Vui lòng không để hành lý của bạn mà không có người trông coi vào bất kỳ lúc nào.",
    "collocations": ["carry-on luggage", "excess luggage", "luggage allowance"],
    "synonyms": ["baggage"],
    "wordFamily": [],
    "day": 21
  },
  {
    "id": "baggage-noun",
    "word": "baggage",
    "baseWord": "baggage",
    "type": "noun",
    "meaning": "hành lý (thường mang đi xa, ký gửi)",
    "pronunciation": "/ˈbæɡɪdʒ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "You can collect your baggage at carousel number 4.",
    "exampleVi": "Bạn có thể nhận hành lý của mình tại băng chuyền số 4.",
    "collocations": ["baggage claim", "baggage allowance", "checked baggage"],
    "synonyms": ["luggage"],
    "wordFamily": [],
    "day": 21
  },
  {
    "id": "ticket-noun",
    "word": "ticket",
    "baseWord": "ticket",
    "type": "noun",
    "meaning": "vé, biên lai phạt",
    "pronunciation": "/ˈtɪkɪt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "I bought a round-trip ticket to Chicago yesterday.",
    "exampleVi": "Tôi đã mua một vé khứ hồi đi Chicago ngày hôm qua.",
    "collocations": ["train ticket", "parking ticket", "purchase a ticket"],
    "synonyms": ["pass", "voucher"],
    "wordFamily": [],
    "day": 21
  },
  {
    "id": "booking-noun",
    "word": "booking",
    "baseWord": "book",
    "type": "noun",
    "meaning": "sự đặt trước (vé, phòng)",
    "pronunciation": "/ˈbʊkɪŋ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We made a booking for a double room at the Grand Hotel.",
    "exampleVi": "Chúng tôi đã đặt trước một phòng đôi tại Khách sạn Grand.",
    "collocations": ["make a booking", "confirm a booking", "booking reference"],
    "synonyms": ["reservation"],
    "wordFamily": ["book", "booked"],
    "day": 21
  },
  {
    "id": "check-in-noun",
    "word": "check-in",
    "baseWord": "check",
    "type": "noun",
    "meaning": "thủ tục đăng ký, quầy làm thủ tục",
    "pronunciation": "/ˈtʃek ɪn/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The flight check-in desk opens two hours before departure.",
    "exampleVi": "Quầy làm thủ tục chuyến bay mở cửa hai giờ trước khi khởi hành.",
    "collocations": ["check-in desk", "check-in counter", "online check-in"],
    "synonyms": [],
    "wordFamily": ["check"],
    "day": 21
  },

  # Day 22
  {
    "id": "board-verb",
    "word": "board",
    "baseWord": "board",
    "type": "verb",
    "meaning": "lên tàu, xe, máy bay",
    "pronunciation": "/bɔːrd/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We will board the plane as soon as the gate opens.",
    "exampleVi": "Chúng tôi sẽ lên máy bay ngay khi cổng mở.",
    "collocations": ["board a flight", "board a train", "ready to board"],
    "synonyms": ["embark"],
    "wordFamily": ["boarding", "boarder"],
    "day": 22
  },
  {
    "id": "disembark-verb",
    "word": "disembark",
    "baseWord": "bark",
    "type": "verb",
    "meaning": "xuống tàu, máy bay",
    "pronunciation": "/ˌdɪsɪmˈbɑːrk/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "Passengers were asked to disembark through the rear exit.",
    "exampleVi": "Hành khách được yêu cầu xuống máy bay qua lối thoát phía sau.",
    "collocations": ["disembark the aircraft", "disembark the ship", "prepare to disembark"],
    "synonyms": ["get off", "alight"],
    "wordFamily": ["embarkation", "disembarkation"],
    "day": 22
  },
  {
    "id": "direct-adjective",
    "word": "direct",
    "baseWord": "direct",
    "type": "adjective",
    "meaning": "trực tiếp, không qua trung gian",
    "pronunciation": "/dəˈrekt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Is there a direct flight from New York to London?",
    "exampleVi": "Có chuyến bay trực tiếp nào từ New York đi Luân Đôn không?",
    "collocations": ["direct flight", "direct route", "direct connection"],
    "synonyms": ["straight", "nonstop"],
    "wordFamily": ["directly", "direction", "director"],
    "day": 22
  },
  {
    "id": "local-adjective",
    "word": "local",
    "baseWord": "local",
    "type": "adjective",
    "meaning": "thuộc về địa phương, chạy tuyến ngắn dừng nhiều ga",
    "pronunciation": "/ˈloʊkl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The local train takes longer because it stops at every station.",
    "exampleVi": "Tàu hỏa chạy tuyến địa phương mất nhiều thời gian hơn vì nó dừng ở mọi nhà ga.",
    "collocations": ["local train", "local transit", "local residents"],
    "synonyms": ["regional"],
    "wordFamily": ["locally", "locality", "localize"],
    "day": 22
  },
  {
    "id": "one-way-adjective",
    "word": "one-way",
    "baseWord": "one-way",
    "type": "adjective",
    "meaning": "một chiều",
    "pronunciation": "/ˈwʌn weɪ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "A one-way ticket is sometimes nearly as expensive as a round-trip.",
    "exampleVi": "Một vé một chiều đôi khi gần như đắt bằng vé khứ hồi.",
    "collocations": ["one-way ticket", "one-way street", "one-way traffic"],
    "synonyms": [],
    "wordFamily": [],
    "day": 22
  },
  {
    "id": "round-trip-adjective",
    "word": "round-trip",
    "baseWord": "round-trip",
    "type": "adjective",
    "meaning": "khứ hồi, hai chiều",
    "pronunciation": "/ˈraʊnd trɪp/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "Booking a round-trip ticket saved us over fifty dollars.",
    "exampleVi": "Đặt vé khứ hồi đã tiết kiệm cho chúng tôi hơn năm mươi đô la.",
    "collocations": ["round-trip ticket", "round-trip fare", "round-trip flight"],
    "synonyms": ["return"],
    "wordFamily": [],
    "day": 22
  },
  {
    "id": "non-refundable-adjective",
    "word": "non-refundable",
    "baseWord": "refund",
    "type": "adjective",
    "meaning": "không được hoàn tiền",
    "pronunciation": "/ˌnɑːn rɪˈfʌndəbl/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "These promotional fares are completely non-refundable.",
    "exampleVi": "Các mức giá vé khuyến mãi này hoàn toàn không được hoàn tiền.",
    "collocations": ["non-refundable deposit", "non-refundable ticket", "non-refundable fee"],
    "synonyms": [],
    "wordFamily": ["refund", "refundable"],
    "day": 22
  },
  {
    "id": "surcharge-noun",
    "word": "surcharge",
    "baseWord": "charge",
    "type": "noun",
    "meaning": "khoản phụ phí, tiền phạt thêm",
    "pronunciation": "/ˈsɜːrtʃɑːrdʒ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 5", "Part 7"],
    "example": "There is a twenty-dollar surcharge for traveling during holidays.",
    "exampleVi": "Có một khoản phụ phí hai mươi đô la cho việc đi lại vào các ngày lễ.",
    "collocations": ["fuel surcharge", "additional surcharge", "impose a surcharge"],
    "synonyms": ["extra fee", "excess charge"],
    "wordFamily": ["charge"],
    "day": 22
  },
  {
    "id": "toll-noun",
    "word": "toll",
    "baseWord": "toll",
    "type": "noun",
    "meaning": "phí qua cầu đường, phí dịch vụ công",
    "pronunciation": "/toʊl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Drivers must pay a toll to cross the Golden Gate Bridge.",
    "exampleVi": "Các tài xế phải trả phí để qua Cầu Cổng Vàng.",
    "collocations": ["toll road", "toll booth", "collect tolls"],
    "synonyms": ["fee", "tax"],
    "wordFamily": [],
    "day": 22
  },
  {
    "id": "highway-noun",
    "word": "highway",
    "baseWord": "highway",
    "type": "noun",
    "meaning": "quốc lộ, xa lộ",
    "pronunciation": "/ˈhaɪweɪ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The highway is currently closed for maintenance.",
    "exampleVi": "Xa lộ hiện đang đóng cửa để bảo trì.",
    "collocations": ["highway patrol", "national highway", "highway toll"],
    "synonyms": ["expressway", "freeway"],
    "wordFamily": [],
    "day": 22
  },
  {
    "id": "detour-noun",
    "word": "detour",
    "baseWord": "detour",
    "type": "noun",
    "meaning": "đường vòng, lối rẽ tạm thời",
    "pronunciation": "/ˈdiːtʊr/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We had to take a detour because the main bridge was under repair.",
    "exampleVi": "Chúng tôi đã phải đi đường vòng vì cây cầu chính đang được sửa chữa.",
    "collocations": ["take a detour", "detour sign", "make a detour"],
    "synonyms": ["diversion", "deviation"],
    "wordFamily": [],
    "day": 22
  },
  {
    "id": "congestion-noun",
    "word": "congestion",
    "baseWord": "congest",
    "type": "noun",
    "meaning": "sự tắc nghẽn, kẹt xe",
    "pronunciation": "/kənˈdʒestʃən/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 4", "Part 5", "Part 7"],
    "example": "Traffic congestion in the city center has worsened over the years.",
    "exampleVi": "Sự kẹt xe ở trung tâm thành phố đã trở nên tồi tệ hơn qua các năm.",
    "collocations": ["traffic congestion", "severely congested", "reduce congestion"],
    "synonyms": ["crowdedness", "blockage"],
    "wordFamily": ["congest", "congested"],
    "day": 22
  },
  {
    "id": "gridlock-noun",
    "word": "gridlock",
    "baseWord": "gridlock",
    "type": "noun",
    "meaning": "tình trạng kẹt xe cứng nhắc, tê liệt hoàn toàn",
    "pronunciation": "/ˈɡrɪdlɑːk/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 4", "Part 7"],
    "example": "A minor accident caused a total gridlock during rush hour.",
    "exampleVi": "Một tai nạn nhỏ đã gây ra tình trạng kẹt xe hoàn toàn trong giờ cao điểm.",
    "collocations": ["total gridlock", "traffic gridlock", "reach a gridlock"],
    "synonyms": ["standstill", "deadlock"],
    "wordFamily": ["gridlocked"],
    "day": 22
  },
  {
    "id": "peak-hours-phrase",
    "word": "peak hours",
    "baseWord": "peak",
    "type": "phrase",
    "meaning": "giờ cao điểm, thời điểm bận rộn nhất",
    "pronunciation": "/piːk ˈaʊərz/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 4", "Part 7"],
    "example": "It is difficult to find parking during peak hours.",
    "exampleVi": "Rất khó tìm được chỗ đỗ xe trong những giờ cao điểm.",
    "collocations": ["during peak hours", "peak travel hours", "avoid peak hours"],
    "synonyms": ["peak times", "rush hour"],
    "wordFamily": ["peak"],
    "day": 22
  },
  {
    "id": "rush-hour-phrase",
    "word": "rush hour",
    "baseWord": "rush",
    "type": "phrase",
    "meaning": "giờ cao điểm di chuyển (đi làm, về nhà)",
    "pronunciation": "/rʌʃ ˈaʊər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 4", "Part 5"],
    "example": "The subways are extremely crowded during the morning rush hour.",
    "exampleVi": "Các ga tàu điện ngầm cực kỳ đông đúc vào giờ cao điểm buổi sáng.",
    "collocations": ["morning rush hour", "evening rush hour", "rush hour traffic"],
    "synonyms": ["peak hours"],
    "wordFamily": ["rush"],
    "day": 22
  },
  {
    "id": "public-transit-phrase",
    "word": "public transit",
    "baseWord": "transit",
    "type": "phrase",
    "meaning": "hệ thống giao thông công cộng",
    "pronunciation": "/ˈpʌblɪk ˈtrænzɪt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 4", "Part 7"],
    "example": "Many cities encourage residents to use public transit to reduce pollution.",
    "exampleVi": "Nhiều thành phố khuyến khích người dân sử dụng giao thông công cộng để giảm ô nhiễm.",
    "collocations": ["use public transit", "public transit system", "access to public transit"],
    "synonyms": ["public transport"],
    "wordFamily": ["transit"],
    "day": 22
  },
  {
    "id": "carpool-verb",
    "word": "carpool",
    "baseWord": "carpool",
    "type": "verb",
    "meaning": "đi chung xe, góp xe đi chung",
    "pronunciation": "/ˈkɑːrpuːl/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We decided to carpool to work to save money on gasoline.",
    "exampleVi": "Chúng tôi đã quyết định đi chung xe đi làm để tiết kiệm tiền xăng.",
    "collocations": ["carpool lane", "carpool to work", "encourage carpooling"],
    "synonyms": ["rideshare"],
    "wordFamily": ["carpooling", "carpooler"],
    "day": 22
  },
  {
    "id": "pedestrian-noun",
    "word": "pedestrian",
    "baseWord": "pedestrian",
    "type": "noun",
    "meaning": "người đi bộ",
    "pronunciation": "/pəˈdestriən/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "This street is closed to vehicles and reserved for pedestrians only.",
    "exampleVi": "Đường phố này cấm phương tiện giao thông và chỉ dành cho người đi bộ.",
    "collocations": ["pedestrian crossing", "pedestrian zone", "pedestrian safety"],
    "synonyms": ["walker", "stroller"],
    "wordFamily": [],
    "day": 22
  },
  {
    "id": "vehicle-noun",
    "word": "vehicle",
    "baseWord": "vehicle",
    "type": "noun",
    "meaning": "phương tiện giao thông, xe cộ",
    "pronunciation": "/ˈviːəkl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Emergency vehicles are allowed to pass through the red light.",
    "exampleVi": "Các phương tiện khẩn cấp được phép đi qua đèn đỏ.",
    "collocations": ["motor vehicle", "commercial vehicle", "electric vehicle"],
    "synonyms": ["transport", "car"],
    "wordFamily": ["vehicular"],
    "day": 22
  },
  {
    "id": "fleet-noun",
    "word": "fleet",
    "baseWord": "fleet",
    "type": "noun",
    "meaning": "đội tàu, đội xe, đội máy bay",
    "pronunciation": "/fliːt/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The delivery company maintains a large fleet of electric vans.",
    "exampleVi": "Công ty giao hàng duy trì một đội xe tải điện lớn.",
    "collocations": ["fleet of vehicles", "fleet maintenance", "manage a fleet"],
    "synonyms": ["convoy", "group"],
    "wordFamily": [],
    "day": 22
  },

  # Day 23
  {
    "id": "vessel-noun",
    "word": "vessel",
    "baseWord": "vessel",
    "type": "noun",
    "meaning": "tàu thủy lớn, thuyền lớn",
    "pronunciation": "/ˈvesl/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 4", "Part 5", "Part 7"],
    "example": "The cargo vessel is carrying goods from Shanghai to Rotterdam.",
    "exampleVi": "Tàu chở hàng đang chở hàng hóa từ Thượng Hải đến Rotterdam.",
    "collocations": ["cargo vessel", "merchant vessel", "vessel crew"],
    "synonyms": ["ship", "boat"],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "cargo-noun",
    "word": "cargo",
    "baseWord": "cargo",
    "type": "noun",
    "meaning": "hàng hóa (vận chuyển bằng đường thủy hoặc đường không)",
    "pronunciation": "/ˈkɑːrɡoʊ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The airport handles thousands of tons of cargo daily.",
    "exampleVi": "Sân bay xử lý hàng ngàn tấn hàng hóa mỗi ngày.",
    "collocations": ["cargo ship", "cargo space", "load cargo"],
    "synonyms": ["freight", "goods", "shipment"],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "freight-noun",
    "word": "freight",
    "baseWord": "freight",
    "type": "noun",
    "meaning": "hàng hóa chuyên chở, dịch vụ chở hàng",
    "pronunciation": "/freɪt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The cost of air freight has doubled over the past year.",
    "exampleVi": "Chi phí vận chuyển hàng hóa bằng đường hàng không đã tăng gấp đôi trong năm qua.",
    "collocations": ["air freight", "freight train", "freight charges"],
    "synonyms": ["cargo", "shipment"],
    "wordFamily": ["freighter"],
    "day": 23
  },
  {
    "id": "carrier-noun",
    "word": "carrier",
    "baseWord": "carry",
    "type": "noun",
    "meaning": "hãng vận chuyển, công ty vận tải",
    "pronunciation": "/ˈkæriər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We need to choose a reliable carrier for our international deliveries.",
    "exampleVi": "Chúng tôi cần chọn một hãng vận chuyển đáng tin cậy cho các đợt giao hàng quốc tế.",
    "collocations": ["common carrier", "mail carrier", "national carrier"],
    "synonyms": ["shipper", "transporter"],
    "wordFamily": ["carry"],
    "day": 23
  },
  {
    "id": "delivery-noun",
    "word": "delivery",
    "baseWord": "deliver",
    "type": "noun",
    "meaning": "sự giao hàng, chuyến giao hàng",
    "pronunciation": "/dɪˈlɪvəri/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We guarantee delivery within three working days.",
    "exampleVi": "Chúng tôi đảm bảo giao hàng trong vòng ba ngày làm việc.",
    "collocations": ["home delivery", "delivery address", "express delivery"],
    "synonyms": ["shipment", "dispatch"],
    "wordFamily": ["deliver", "deliverer"],
    "day": 23
  },
  {
    "id": "courier-noun",
    "word": "courier",
    "baseWord": "courier",
    "type": "noun",
    "meaning": "người chuyển phát nhanh, công ty chuyển phát nhanh",
    "pronunciation": "/ˈkʊriər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The document was sent by courier to ensure quick arrival.",
    "exampleVi": "Tài liệu được gửi bằng chuyển phát nhanh để đảm bảo đến nơi nhanh chóng.",
    "collocations": ["by courier", "courier service", "local courier"],
    "synonyms": ["messenger", "carrier"],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "expedite-verb",
    "word": "expedite",
    "baseWord": "expedite",
    "type": "verb",
    "meaning": "xúc tiến, đẩy nhanh tiến trình",
    "pronunciation": "/ˈekspədaɪt/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 6", "Part 7"],
    "example": "We can pay an extra fee to expedite the shipping process.",
    "exampleVi": "Chúng tôi có thể trả thêm một khoản phí để đẩy nhanh quá trình vận chuyển.",
    "collocations": ["expedite delivery", "expedite the process", "expedite shipment"],
    "synonyms": ["accelerate", "hasten", "speed up"],
    "wordFamily": ["expeditious", "expeditiously", "expedient"],
    "day": 23
  },
  {
    "id": "haul-verb",
    "word": "haul",
    "baseWord": "haul",
    "type": "verb",
    "meaning": "kéo, chở hàng bằng xe tải chuyên dụng đi xa",
    "pronunciation": "/hɔːl/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "Large trucks are used to haul logs from the forest to the mill.",
    "exampleVi": "Những chiếc xe tải lớn được sử dụng để chở gỗ từ rừng đến nhà máy.",
    "collocations": ["haul cargo", "long-haul flight", "haulage company"],
    "synonyms": ["drag", "tow", "transport"],
    "wordFamily": ["haulage", "hauler"],
    "day": 23
  },
  {
    "id": "transport-verb",
    "word": "transport",
    "baseWord": "transport",
    "type": "verb",
    "meaning": "vận chuyển, chuyên chở",
    "pronunciation": "/trænˈspɔːrt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Pipelines are used to transport oil over long distances.",
    "exampleVi": "Đường ống được sử dụng để vận chuyển dầu đi khoảng cách xa.",
    "collocations": ["transport goods", "transport passengers", "transport by rail"],
    "synonyms": ["convey", "carry", "ship"],
    "wordFamily": ["transportation", "transporter"],
    "day": 23
  },
  {
    "id": "freeway-noun",
    "word": "freeway",
    "baseWord": "freeway",
    "type": "noun",
    "meaning": "đường cao tốc không thu phí",
    "pronunciation": "/ˈfriːweɪ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The traffic on the freeway is moving very slowly due to construction.",
    "exampleVi": "Giao thông trên đường cao tốc đang di chuyển rất chậm do công trình xây dựng.",
    "collocations": ["on the freeway", "freeway traffic", "freeway exit"],
    "synonyms": ["highway", "expressway"],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "customs-noun",
    "word": "customs",
    "baseWord": "custom",
    "type": "noun",
    "meaning": "hải quan, thuế nhập khẩu",
    "pronunciation": "/ˈkʌstəmz/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "You must go through customs when arriving from a foreign country.",
    "exampleVi": "Bạn phải đi qua cửa hải quan khi đến từ nước ngoài.",
    "collocations": ["customs officer", "customs declaration", "go through customs"],
    "synonyms": ["duty", "tariff"],
    "wordFamily": ["custom", "customary"],
    "day": 23
  },
  {
    "id": "declaration-noun",
    "word": "declaration",
    "baseWord": "declare",
    "type": "noun",
    "meaning": "sự khai báo, tờ khai hàng hóa",
    "pronunciation": "/ˌdekləˈreɪʃn/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Please fill out this customs declaration before landing.",
    "exampleVi": "Vui lòng điền vào tờ khai hải quan này trước khi hạ cánh.",
    "collocations": ["customs declaration", "make a declaration", "written declaration"],
    "synonyms": ["announcement", "statement"],
    "wordFamily": ["declare", "declarative"],
    "day": 23
  },
  {
    "id": "duty-free-adjective",
    "word": "duty-free",
    "baseWord": "duty-free",
    "type": "adjective",
    "meaning": "miễn thuế",
    "pronunciation": "/ˌduːti ˈfriː/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 7"],
    "example": "Passengers can buy cheap perfume at the duty-free shop.",
    "exampleVi": "Hành khách có thể mua nước hoa giá rẻ tại cửa hàng miễn thuế.",
    "collocations": ["duty-free shop", "duty-free goods", "duty-free allowance"],
    "synonyms": ["tax-free"],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "passport-noun",
    "word": "passport",
    "baseWord": "passport",
    "type": "noun",
    "meaning": "hộ chiếu",
    "pronunciation": "/ˈpæspɔːrt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "You need a valid passport to travel abroad.",
    "exampleVi": "Bạn cần một hộ chiếu hợp lệ để đi du lịch nước ngoài.",
    "collocations": ["passport control", "valid passport", "passport photo"],
    "synonyms": [],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "visa-noun",
    "word": "visa",
    "baseWord": "visa",
    "type": "noun",
    "meaning": "thị thực, thị thực nhập cảnh",
    "pronunciation": "/ˈviːzə/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "He applied for a business visa to visit the company's branch in Germany.",
    "exampleVi": "Anh ấy đã nộp đơn xin thị thực công tác để đến thăm chi nhánh của công ty ở Đức.",
    "collocations": ["business visa", "tourist visa", "apply for a visa"],
    "synonyms": [],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "embassy-noun",
    "word": "embassy",
    "baseWord": "embassy",
    "type": "noun",
    "meaning": "đại sứ quán",
    "pronunciation": "/ˈembəsi/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 7"],
    "example": "We had to go to the American Embassy to get our visas.",
    "exampleVi": "Chúng tôi đã phải đến Đại sứ quán Mỹ để xin thị thực.",
    "collocations": ["foreign embassy", "embassy official", "visit the embassy"],
    "synonyms": [],
    "wordFamily": [],
    "day": 23
  },
  {
    "id": "consulate-noun",
    "word": "consulate",
    "baseWord": "consul",
    "type": "noun",
    "meaning": "lãnh sự quán",
    "pronunciation": "/ˈkɑːnsələt/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "Contact the British consulate if you lose your passport.",
    "exampleVi": "Hãy liên hệ với lãnh sự quán Anh nếu bạn bị mất hộ chiếu.",
    "collocations": ["local consulate", "consulate general", "contact the consulate"],
    "synonyms": [],
    "wordFamily": ["consul", "consular"],
    "day": 23
  },
  {
    "id": "border-noun",
    "word": "border",
    "baseWord": "border",
    "type": "noun",
    "meaning": "biên giới",
    "pronunciation": "/ˈbɔːrdər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Guards check all cars crossing the border between the two countries.",
    "exampleVi": "Lực lượng bảo vệ kiểm tra tất cả các xe ô tô đi qua biên giới giữa hai quốc gia.",
    "collocations": ["cross the border", "border control", "border crossing"],
    "synonyms": ["frontier", "boundary"],
    "wordFamily": ["borderline"],
    "day": 23
  },
  {
    "id": "immigration-noun",
    "word": "immigration",
    "baseWord": "migrate",
    "type": "noun",
    "meaning": "sự nhập cư, phòng quản lý nhập cảnh",
    "pronunciation": "/ˌɪmɪˈɡreɪʃn/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "He had to stand in a long queue at immigration.",
    "exampleVi": "Anh ấy đã phải đứng xếp hàng dài tại khu vực kiểm soát nhập cảnh.",
    "collocations": ["immigration officer", "immigration control", "illegal immigration"],
    "synonyms": [],
    "wordFamily": ["immigrant", "immigrate"],
    "day": 23
  },
  {
    "id": "customs-clearance-phrase",
    "word": "customs clearance",
    "baseWord": "clear",
    "type": "phrase",
    "meaning": "sự thông quan, làm thủ tục hải quan cho hàng hóa",
    "pronunciation": "/ˈkʌstəmz ˈklɪrəns/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The import company handles all the paperwork for customs clearance.",
    "exampleVi": "Công ty nhập khẩu xử lý tất cả giấy tờ để làm thủ tục thông quan hải quan.",
    "collocations": ["obtain customs clearance", "customs clearance process", "customs clearance agent"],
    "synonyms": ["clearance"],
    "wordFamily": ["clear", "clearance"],
    "day": 23
  },

  # Day 24
  {
    "id": "cruise-noun",
    "word": "cruise",
    "baseWord": "cruise",
    "type": "noun",
    "meaning": "cuộc hành trình chơi trên tàu thủy, du thuyền",
    "pronunciation": "/kruːz/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 7"],
    "example": "They took a two-week cruise around the Caribbean.",
    "exampleVi": "Họ đã đi một chuyến du thuyền kéo dài hai tuần quanh vùng Caribe.",
    "collocations": ["cruise ship", "cruise line", "go on a cruise"],
    "synonyms": ["voyage"],
    "wordFamily": ["cruiser"],
    "day": 24
  },
  {
    "id": "charter-verb",
    "word": "charter",
    "baseWord": "charter",
    "type": "verb",
    "meaning": "thuê trọn gói (tàu, xe, máy bay)",
    "pronunciation": "/ˈtʃɑːrtər/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The travel agency decided to charter a plane for the tour group.",
    "exampleVi": "Đại lý du lịch đã quyết định thuê trọn gói một chiếc máy bay cho nhóm du khách.",
    "collocations": ["charter a plane", "charter flight", "charter company"],
    "synonyms": ["lease", "hire"],
    "wordFamily": ["chartered"],
    "day": 24
  },
  {
    "id": "rent-verb",
    "word": "rent",
    "baseWord": "rent",
    "type": "verb",
    "meaning": "thuê (nhà, xe, đồ dùng trong thời gian ngắn)",
    "pronunciation": "/rent/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We plan to rent a car during our stay in California.",
    "exampleVi": "Chúng tôi dự định thuê một chiếc xe hơi trong suốt kỳ lưu trú tại California.",
    "collocations": ["rent a car", "rent an apartment", "rent for a week"],
    "synonyms": ["hire", "lease"],
    "wordFamily": ["rental", "renter", "rented"],
    "day": 24
  },
  {
    "id": "rental-noun",
    "word": "rental",
    "baseWord": "rent",
    "type": "noun",
    "meaning": "sự thuê mướn, tiền thuê, xe cho thuê",
    "pronunciation": "/ˈrentl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Car rentals are usually cheaper if you book in advance.",
    "exampleVi": "Thuê xe hơi thường rẻ hơn nếu bạn đặt trước.",
    "collocations": ["car rental", "rental agreement", "rental agency"],
    "synonyms": ["lease", "hire"],
    "wordFamily": ["rent", "renter"],
    "day": 24
  },
  {
    "id": "mileage-noun",
    "word": "mileage",
    "baseWord": "mile",
    "type": "noun",
    "meaning": "tổng số dặm đã đi, mức tiêu hao nhiên liệu",
    "pronunciation": "/ˈmaɪlɪdʒ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "You will get unlimited mileage with this rental agreement.",
    "exampleVi": "Bạn sẽ nhận được số dặm đi không giới hạn với hợp đồng thuê xe này.",
    "collocations": ["unlimited mileage", "high mileage", "mileage allowance"],
    "synonyms": [],
    "wordFamily": ["mile"],
    "day": 24
  },
  {
    "id": "fuel-noun",
    "word": "fuel",
    "baseWord": "fuel",
    "type": "noun",
    "meaning": "nhiên liệu",
    "pronunciation": "/ˈfjuːəl/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 5", "Part 7"],
    "example": "Please return the rental car with a full tank of fuel.",
    "exampleVi": "Vui lòng trả xe thuê với bình nhiên liệu đầy.",
    "collocations": ["fuel consumption", "fuel efficiency", "fossil fuel"],
    "synonyms": ["gas", "gasoline", "petrol"],
    "wordFamily": [],
    "day": 24
  },
  {
    "id": "servicing-noun",
    "word": "servicing",
    "baseWord": "serve",
    "type": "noun",
    "meaning": "việc bảo dưỡng (máy móc, xe cộ)",
    "pronunciation": "/ˈsɜːrvɪsɪŋ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 5", "Part 7"],
    "example": "The bus is currently out of operation for regular servicing.",
    "exampleVi": "Chiếc xe buýt hiện đang ngừng hoạt động để bảo dưỡng định kỳ.",
    "collocations": ["regular servicing", "car servicing", "scheduled servicing"],
    "synonyms": ["maintenance"],
    "wordFamily": ["service", "servant", "serve"],
    "day": 24
  },
  {
    "id": "breakdown-noun",
    "word": "breakdown",
    "baseWord": "break",
    "type": "noun",
    "meaning": "sự hỏng hóc giữa chừng, sự chết máy xe",
    "pronunciation": "/ˈbreɪkdaʊn/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5"],
    "example": "We missed the meeting because of a sudden breakdown on the highway.",
    "exampleVi": "Chúng tôi đã lỡ cuộc họp vì chiếc xe bất ngờ bị hỏng trên xa lộ.",
    "collocations": ["sudden breakdown", "mechanical breakdown", "breakdown service"],
    "synonyms": ["failure", "malfunction"],
    "wordFamily": ["break"],
    "day": 24
  },
  {
    "id": "accident-noun",
    "word": "accident",
    "baseWord": "accident",
    "type": "noun",
    "meaning": "tai nạn, sự cố bất ngờ",
    "pronunciation": "/ˈæksɪdənt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The traffic was delayed due to a car accident.",
    "exampleVi": "Giao thông bị chậm lại do một vụ tai nạn xe hơi.",
    "collocations": ["car accident", "minor accident", "fatal accident"],
    "synonyms": ["mishap", "collision"],
    "wordFamily": ["accidental", "accidentally"],
    "day": 24
  },
  {
    "id": "insurance-noun",
    "word": "insurance",
    "baseWord": "insure",
    "type": "noun",
    "meaning": "bảo hiểm",
    "pronunciation": "/ɪnˈʃʊrəns/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "We highly recommend purchasing travel insurance before your trip.",
    "exampleVi": "Chúng tôi thực sự khuyên bạn nên mua bảo hiểm du lịch trước chuyến đi.",
    "collocations": ["travel insurance", "car insurance", "insurance policy"],
    "synonyms": ["assurance", "coverage"],
    "wordFamily": ["insure", "insurer", "insured"],
    "day": 24
  },
  {
    "id": "indemnity-noun",
    "word": "indemnity",
    "baseWord": "indemnify",
    "type": "noun",
    "meaning": "sự bồi thường thiệt hại, sự bảo đảm bồi thường",
    "pronunciation": "/ɪnˈdemnəti/",
    "topic": "Travel & Transportation",
    "frequency": "low",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The rental company offers an indemnity package to cover any collision costs.",
    "exampleVi": "Công ty cho thuê xe cung cấp một gói bảo đảm bồi thường để đền bù mọi chi phí va chạm.",
    "collocations": ["indemnity insurance", "letter of indemnity", "claim indemnity"],
    "synonyms": ["compensation", "indemnification", "redress"],
    "wordFamily": ["indemnify"],
    "day": 24
  },
  {
    "id": "liability-noun",
    "word": "liability",
    "baseWord": "liable",
    "type": "noun",
    "meaning": "trách nhiệm pháp lý, khoản nợ",
    "pronunciation": "/ˌlaɪəˈbɪləti/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "hard",
    "partTags": ["Part 5", "Part 6", "Part 7"],
    "example": "The airline denied any liability for the lost baggage.",
    "exampleVi": "Hãng hàng không từ chối mọi trách nhiệm pháp lý đối với hành lý bị thất lạc.",
    "collocations": ["accept liability", "liability insurance", "legal liability"],
    "synonyms": ["accountability", "responsibility"],
    "wordFamily": ["liable"],
    "day": 24
  },
  {
    "id": "driver-noun",
    "word": "driver",
    "baseWord": "drive",
    "type": "noun",
    "meaning": "tài xế, người lái xe",
    "pronunciation": "/ˈdraɪvər/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The bus driver helped the tourists with their luggage.",
    "exampleVi": "Tài xế xe buýt đã giúp đỡ khách du lịch với hành lý của họ.",
    "collocations": ["bus driver", "taxi driver", "careless driver"],
    "synonyms": ["operator", "chauffeur"],
    "wordFamily": ["drive", "driving"],
    "day": 24
  },
  {
    "id": "chauffeur-noun",
    "word": "chauffeur",
    "baseWord": "chauffeur",
    "type": "noun",
    "meaning": "tài xế riêng (cho xe sang, người quan trọng)",
    "pronunciation": "/ʃoʊˈfɜːr/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "A professional chauffeur met the executives at the airport.",
    "exampleVi": "Một tài xế riêng chuyên nghiệp đã đón các giám đốc điều hành tại sân bay.",
    "collocations": ["hire a chauffeur", "private chauffeur", "chauffeur-driven car"],
    "synonyms": ["driver"],
    "wordFamily": ["chauffeur-driven"],
    "day": 24
  },
  {
    "id": "cab-noun",
    "word": "cab",
    "baseWord": "cab",
    "type": "noun",
    "meaning": "xe taxi",
    "pronunciation": "/kæb/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We decided to take a cab since it was raining heavily.",
    "exampleVi": "Chúng tôi đã quyết định bắt một chiếc taxi vì trời đang mưa rất to.",
    "collocations": ["take a cab", "yellow cab", "cab driver"],
    "synonyms": ["taxi"],
    "wordFamily": [],
    "day": 24
  },
  {
    "id": "taxi-noun",
    "word": "taxi",
    "baseWord": "taxi",
    "type": "noun",
    "meaning": "xe taxi",
    "pronunciation": "/ˈtæksi/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "There is a taxi stand right outside the station terminal.",
    "exampleVi": "Có một bến đỗ xe taxi ngay bên ngoài nhà ga.",
    "collocations": ["taxi stand", "taxi fare", "call a taxi"],
    "synonyms": ["cab"],
    "wordFamily": [],
    "day": 24
  },
  {
    "id": "ridesharing-noun",
    "word": "ridesharing",
    "baseWord": "share",
    "type": "noun",
    "meaning": "dịch vụ đi chung xe công nghệ (như Uber, Grab)",
    "pronunciation": "/ˈraɪdʃerɪŋ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Ridesharing apps have transformed urban transportation.",
    "exampleVi": "Các ứng dụng đi chung xe đã làm biến đổi giao thông đô thị.",
    "collocations": ["ridesharing app", "ridesharing service", "use ridesharing"],
    "synonyms": ["carpooling"],
    "wordFamily": ["share", "sharing", "ride"],
    "day": 24
  },
  {
    "id": "subway-noun",
    "word": "subway",
    "baseWord": "subway",
    "type": "noun",
    "meaning": "tàu điện ngầm, đường ngầm",
    "pronunciation": "/ˈsʌbweɪ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We took the subway to avoid the gridlock on the surface streets.",
    "exampleVi": "Chúng tôi đã đi tàu điện ngầm để tránh tình trạng tắc nghẽn trên các đường phố phía trên.",
    "collocations": ["subway station", "subway train", "ride the subway"],
    "synonyms": ["metro", "underground"],
    "wordFamily": [],
    "day": 24
  },
  {
    "id": "railway-noun",
    "word": "railway",
    "baseWord": "railway",
    "type": "noun",
    "meaning": "đường sắt, hệ thống đường ray",
    "pronunciation": "/ˈreɪlweɪ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The country is expanding its high-speed railway network.",
    "exampleVi": "Quốc gia này đang mở rộng mạng lưới đường sắt tốc độ cao.",
    "collocations": ["railway station", "railway network", "railway track"],
    "synonyms": ["railroad"],
    "wordFamily": [],
    "day": 24
  },
  {
    "id": "locomotive-noun",
    "word": "locomotive",
    "baseWord": "motive",
    "type": "noun",
    "meaning": "đầu máy xe lửa",
    "pronunciation": "/ˌloʊkəˈmoʊtɪv/",
    "topic": "Travel & Transportation",
    "frequency": "low",
    "level": "hard",
    "partTags": ["Part 5", "Part 7"],
    "example": "The diesel locomotive was replaced by an electric model.",
    "exampleVi": "Đầu máy chạy dầu diesel đã được thay thế bằng một mô hình chạy điện.",
    "collocations": ["steam locomotive", "diesel locomotive", "electric locomotive"],
    "synonyms": ["engine"],
    "wordFamily": ["motion", "locomotion"],
    "day": 24
  },

  # Day 25
  {
    "id": "lodging-noun",
    "word": "lodging",
    "baseWord": "lodge",
    "type": "noun",
    "meaning": "chỗ nghỉ tạm thời, nơi lưu trú",
    "pronunciation": "/ˈlɑːdʒɪŋ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The tour package includes travel and lodging costs.",
    "exampleVi": "Gói du lịch bao gồm chi phí đi lại và nơi lưu trú.",
    "collocations": ["provide lodging", "overnight lodging", "lodging options"],
    "synonyms": ["accommodation", "dwelling"],
    "wordFamily": ["lodge", "lodger"],
    "day": 25
  },
  {
    "id": "hotel-noun",
    "word": "hotel",
    "baseWord": "hotel",
    "type": "noun",
    "meaning": "khách sạn",
    "pronunciation": "/hoʊˈtel/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The hotel lobby was decorated with beautiful flowers.",
    "exampleVi": "Sảnh khách sạn được trang trí bằng những bông hoa tuyệt đẹp.",
    "collocations": ["hotel room", "hotel guest", "boutique hotel"],
    "synonyms": ["inn", "lodging"],
    "wordFamily": ["hotelier"],
    "day": 25
  },
  {
    "id": "motel-noun",
    "word": "motel",
    "baseWord": "motel",
    "type": "noun",
    "meaning": "khách sạn dọc đường (cho người đi xe ô tô)",
    "pronunciation": "/moʊˈtel/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "easy",
    "partTags": ["Part 3", "Part 7"],
    "example": "We stayed at a cheap roadside motel for the night.",
    "exampleVi": "Chúng tôi đã nghỉ tại một nhà nghỉ ven đường giá rẻ qua đêm.",
    "collocations": ["roadside motel", "cheap motel", "motel room"],
    "synonyms": ["motor inn"],
    "wordFamily": [],
    "day": 25
  },
  {
    "id": "inn-noun",
    "word": "inn",
    "baseWord": "inn",
    "type": "noun",
    "meaning": "nhà trọ, khách sạn nhỏ cổ kính",
    "pronunciation": "/ɪn/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 7"],
    "example": "The historic inn offered comfortable rooms and home-cooked meals.",
    "exampleVi": "Quán trọ lâu đời cung cấp những phòng nghỉ thoải mái và các bữa ăn tự nấu như ở nhà.",
    "collocations": ["country inn", "historic inn", "stay at an inn"],
    "synonyms": ["hotel", "tavern"],
    "wordFamily": ["keeper"],
    "day": 25
  },
  {
    "id": "hostel-noun",
    "word": "hostel",
    "baseWord": "hostel",
    "type": "noun",
    "meaning": "nhà nghỉ giá rẻ (cho sinh viên, khách du lịch bụi)",
    "pronunciation": "/ˈhɑːstl/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "easy",
    "partTags": ["Part 3", "Part 7"],
    "example": "Staying in a youth hostel is a good way to meet other travelers.",
    "exampleVi": "Nghỉ tại nhà nghỉ thanh niên là một cách tốt để gặp gỡ các du khách khác.",
    "collocations": ["youth hostel", "hostel room", "book a hostel"],
    "synonyms": ["dormitory"],
    "wordFamily": [],
    "day": 25
  },
  {
    "id": "resort-noun",
    "word": "resort",
    "baseWord": "resort",
    "type": "noun",
    "meaning": "khu nghỉ dưỡng",
    "pronunciation": "/rɪˈzɔːrt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The seaside resort offers various water sports activities.",
    "exampleVi": "Khu nghỉ dưỡng bên bờ biển cung cấp các hoạt động thể thao dưới nước khác nhau.",
    "collocations": ["seaside resort", "luxury resort", "resort town"],
    "synonyms": ["spa", "vacation spot"],
    "wordFamily": ["resort"],
    "day": 25
  },
  {
    "id": "amenity-noun",
    "word": "amenity",
    "baseWord": "amenity",
    "type": "noun",
    "meaning": "tiện nghi, dịch vụ gia tăng (trong khách sạn, tòa nhà)",
    "pronunciation": "/əˈmenəti/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "hard",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The hotel features high-end amenities, including an indoor pool.",
    "exampleVi": "Khách sạn có các tiện nghi cao cấp, bao gồm một hồ bơi trong nhà.",
    "collocations": ["modern amenities", "hotel amenities", "basic amenities"],
    "synonyms": ["facility", "convenience"],
    "wordFamily": [],
    "day": 25
  },
  {
    "id": "service-noun",
    "word": "service",
    "baseWord": "serve",
    "type": "noun",
    "meaning": "dịch vụ, sự phục vụ",
    "pronunciation": "/ˈsɜːrvɪs/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The shuttle service is available twenty-four hours a day.",
    "exampleVi": "Dịch vụ xe đưa đón hoạt động hai mươi tư giờ một ngày.",
    "collocations": ["customer service", "room service", "excellent service"],
    "synonyms": ["assistance"],
    "wordFamily": ["serve", "servant", "servicing"],
    "day": 25
  },
  {
    "id": "reception-noun",
    "word": "reception",
    "baseWord": "receive",
    "type": "noun",
    "meaning": "quầy tiếp tân, sự đón nhận, buổi tiệc chiêu đãi",
    "pronunciation": "/rɪˈsepʃn/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Please leave your room key at the reception when you check out.",
    "exampleVi": "Vui lòng để lại chìa khóa phòng tại quầy tiếp tân khi bạn trả phòng.",
    "collocations": ["reception desk", "wedding reception", "reception area"],
    "synonyms": ["front desk"],
    "wordFamily": ["receive", "recipient", "receptive"],
    "day": 25
  },
  {
    "id": "concierge-noun",
    "word": "concierge",
    "baseWord": "concierge",
    "type": "noun",
    "meaning": "nhân viên hỗ trợ khách hàng tại khách sạn",
    "pronunciation": "/koʊnˈsjerʒ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "hard",
    "partTags": ["Part 3", "Part 7"],
    "example": "The concierge helped us book tickets for the theater show.",
    "exampleVi": "Nhân viên hỗ trợ khách hàng đã giúp chúng tôi đặt vé xem chương trình kịch.",
    "collocations": ["hotel concierge", "ask the concierge", "concierge desk"],
    "synonyms": ["assistant", "porter"],
    "wordFamily": [],
    "day": 25
  },
  {
    "id": "lobby-noun",
    "word": "lobby",
    "baseWord": "lobby",
    "type": "noun",
    "meaning": "sảnh chờ, hành lang",
    "pronunciation": "/ˈlɑːbi/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We met in the hotel lobby to discuss the tour schedule.",
    "exampleVi": "Chúng tôi gặp nhau ở sảnh khách sạn để thảo luận về lịch trình tham quan.",
    "collocations": ["hotel lobby", "building lobby", "wait in the lobby"],
    "synonyms": ["foyer", "hallway"],
    "wordFamily": ["lobbyist"],
    "day": 25
  },
  {
    "id": "suite-noun",
    "word": "suite",
    "baseWord": "suite",
    "type": "noun",
    "meaning": "dãy phòng, căn hộ cao cấp trong khách sạn",
    "pronunciation": "/swiːt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 7"],
    "example": "The executive suite has a spectacular view of the harbor.",
    "exampleVi": "Căn hộ thượng hạng dành cho ban điều hành có tầm nhìn ngoạn mục ra bến cảng.",
    "collocations": ["executive suite", "hotel suite", "presidential suite"],
    "synonyms": ["apartment"],
    "wordFamily": [],
    "day": 25
  },
  {
    "id": "vacancy-noun",
    "word": "vacancy",
    "baseWord": "vacant",
    "type": "noun",
    "meaning": "phòng trống (khách sạn), vị trí trống (công việc)",
    "pronunciation": "/ˈveɪkənsi/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "The neon sign outside the motel read 'No Vacancy'.",
    "exampleVi": "Biển báo neon bên ngoài nhà nghỉ ghi 'Hết phòng trống'.",
    "collocations": ["no vacancy", "job vacancy", "fill a vacancy"],
    "synonyms": ["opening", "empty room"],
    "wordFamily": ["vacant", "vacate", "vacation"],
    "day": 25
  },
  {
    "id": "occupied-adjective",
    "word": "occupied",
    "baseWord": "occupy",
    "type": "adjective",
    "meaning": "đang bị sử dụng, đang bận",
    "pronunciation": "/ˈɑːkjupaɪd/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "This seat is already occupied by another passenger.",
    "exampleVi": "Chỗ ngồi này đã được sử dụng bởi một hành khách khác.",
    "collocations": ["fully occupied", "occupied seat", "occupied room"],
    "synonyms": ["taken", "busy", "unavailable"],
    "wordFamily": ["occupy", "occupant", "occupation"],
    "day": 25
  },
  {
    "id": "check-out-noun",
    "word": "check-out",
    "baseWord": "check",
    "type": "noun",
    "meaning": "thủ tục trả phòng, quầy thanh toán (siêu thị)",
    "pronunciation": "/ˈtʃek aʊt/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "The standard check-out time is eleven o'clock in the morning.",
    "exampleVi": "Thời gian trả phòng tiêu chuẩn là mười một giờ sáng.",
    "collocations": ["check-out time", "express check-out", "check-out desk"],
    "synonyms": [],
    "wordFamily": ["check"],
    "day": 25
  },
  {
    "id": "housekeeping-noun",
    "word": "housekeeping",
    "baseWord": "house",
    "type": "noun",
    "meaning": "bộ phận dọn phòng, công việc dọn dẹp nhà cửa",
    "pronunciation": "/ˈhaʊskiːpɪŋ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 7"],
    "example": "You can contact housekeeping if you need extra towels.",
    "exampleVi": "Bạn có thể liên hệ với bộ phận dọn phòng nếu bạn cần thêm khăn tắm.",
    "collocations": ["housekeeping department", "housekeeping service", "call housekeeping"],
    "synonyms": ["cleaning service"],
    "wordFamily": ["housekeeper", "housekeep"],
    "day": 25
  },
  {
    "id": "room-service-noun",
    "word": "room service",
    "baseWord": "serve",
    "type": "noun",
    "meaning": "dịch vụ phục vụ đồ ăn tại phòng khách sạn",
    "pronunciation": "/ruːm ˈsɜːrvɪs/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5"],
    "example": "We ordered club sandwiches from room service for dinner.",
    "exampleVi": "Chúng tôi đã đặt bánh mì kẹp từ dịch vụ phục vụ tại phòng cho bữa tối.",
    "collocations": ["order room service", "room service menu", "room service charge"],
    "synonyms": [],
    "wordFamily": ["service", "serve"],
    "day": 25
  },
  {
    "id": "free-of-charge-phrase",
    "word": "free of charge",
    "baseWord": "free",
    "type": "phrase",
    "meaning": "miễn phí, không phải thanh toán tiền",
    "pronunciation": "/friː əv tʃɑːrdʒ/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Wireless internet access is provided free of charge for all guests.",
    "exampleVi": "Truy cập internet không dây được cung cấp miễn phí cho tất cả khách hàng.",
    "collocations": ["available free of charge", "provided free of charge", "service free of charge"],
    "synonyms": ["complimentary", "gratuitous", "free"],
    "wordFamily": ["free", "charge"],
    "day": 25
  },
  {
    "id": "valet-noun",
    "word": "valet",
    "baseWord": "valet",
    "type": "noun",
    "meaning": "nhân viên đỗ xe hộ, người hầu phòng",
    "pronunciation": "/væˈleɪ/",
    "topic": "Travel & Transportation",
    "frequency": "medium",
    "level": "medium",
    "partTags": ["Part 3", "Part 5", "Part 7"],
    "example": "Leave your car keys with the valet at the hotel entrance.",
    "exampleVi": "Hãy để lại chìa khóa xe của bạn cho nhân viên đỗ xe tại lối vào khách sạn.",
    "collocations": ["valet parking", "valet service", "hotel valet"],
    "synonyms": ["attendant"],
    "wordFamily": [],
    "day": 25
  },
  {
    "id": "shuttle-service-phrase",
    "word": "shuttle service",
    "baseWord": "shuttle",
    "type": "phrase",
    "meaning": "dịch vụ xe đưa đón chạy thường xuyên",
    "pronunciation": "/ˈʃʌtl ˈsɜːrvɪs/",
    "topic": "Travel & Transportation",
    "frequency": "high",
    "level": "easy",
    "partTags": ["Part 3", "Part 4", "Part 7"],
    "example": "The hotel offers a complimentary shuttle service to nearby attractions.",
    "exampleVi": "Khách sạn cung cấp dịch vụ xe đưa đón miễn phí đến các điểm thu hút khách du lịch lân cận.",
    "collocations": ["complimentary shuttle service", "airport shuttle service", "provide a shuttle service"],
    "synonyms": ["transfer service"],
    "wordFamily": ["shuttle", "service"],
    "day": 25
  }
]

output_path = r'g:\InLit\scripts\vocab-batches\vocab_day_021_025.json'
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"Successfully generated {len(data)} entries for Days 21-25.")
